// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"fmt"
	"net/url"
)

// AffiliateReferralSessionService handles AffiliateReferralSessions operations.
type AffiliateReferralSessionService struct {
	client *Client
}

// AffiliateReferralSessionsListParams contains the parameters for List.
type AffiliateReferralSessionsListParams struct {
	// AffiliateID is filter by affiliate ID.
	AffiliateID *int `url:"affiliate_id,omitempty" json:"-"`
	// Active is return active or expired sessions.
	Active *bool `url:"active,omitempty" json:"-"`
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
}

// List affiliate referral sessions
// List store-scoped referral attribution sessions. Session identifiers are sensitive. Requires `affiliate` and `affiliate:sensitive`. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *AffiliateReferralSessionService) List(ctx context.Context, params *AffiliateReferralSessionsListParams, opts ...RequestOption) *Iterator[ListAffiliateReferralSessionsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("listAffiliateReferralSessions", false)}, opts...)
	return newIterator[ListAffiliateReferralSessionsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", "/v2/affiliate-referral-sessions", params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *AffiliateReferralSessionService) ListWithResponse(ctx context.Context, params *AffiliateReferralSessionsListParams, opts ...RequestOption) (*RawResponse[*Iterator[ListAffiliateReferralSessionsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Get retrieve an affiliate referral session
// Retrieve one store-scoped referral attribution session. Requires `affiliate` and `affiliate:sensitive`. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *AffiliateReferralSessionService) Get(ctx context.Context, referralSession int, opts ...RequestOption) (*SdkGetAffiliateReferralSessionResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getAffiliateReferralSession", false)}, opts...)
	var result SdkGetAffiliateReferralSessionResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/affiliate-referral-sessions/%s", url.PathEscape(fmt.Sprint(referralSession))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *AffiliateReferralSessionService) GetWithResponse(ctx context.Context, referralSession int, opts ...RequestOption) (*RawResponse[*SdkGetAffiliateReferralSessionResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, referralSession, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
