// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"fmt"
	"net/url"
)

// AffiliateReferralService handles AffiliateReferrals operations.
type AffiliateReferralService struct {
	client *Client
}

// AffiliateReferralsListParams contains the parameters for List.
type AffiliateReferralsListParams struct {
	// AffiliateID is filter by store affiliate ID.
	AffiliateID *int `url:"affiliate_id,omitempty" json:"-"`
	// OrderID is filter by attributed Order ID.
	OrderID *int `url:"order_id,omitempty" json:"-"`
	// Status is filter by referral status.
	Status *AffiliateReferralsStatus `url:"status,omitempty" json:"-"`
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
}

// List affiliate referrals
// List store referrals with their attributed order and purchase line item. Requires the `affiliate` credential ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *AffiliateReferralService) List(ctx context.Context, params *AffiliateReferralsListParams, opts ...RequestOption) *Iterator[ListAffiliateReferralsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("listAffiliateReferrals", false)}, opts...)
	return newIterator[ListAffiliateReferralsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", "/v2/affiliate-referrals", params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *AffiliateReferralService) ListWithResponse(ctx context.Context, params *AffiliateReferralsListParams, opts ...RequestOption) (*RawResponse[*Iterator[ListAffiliateReferralsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Get retrieve an affiliate referral
// Retrieve a referral and its attributed order and purchase line item. Requires the `affiliate` credential ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *AffiliateReferralService) Get(ctx context.Context, referral int, opts ...RequestOption) (*SdkGetAffiliateReferralResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getAffiliateReferral", false)}, opts...)
	var result SdkGetAffiliateReferralResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/affiliate-referrals/%s", url.PathEscape(fmt.Sprint(referral))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *AffiliateReferralService) GetWithResponse(ctx context.Context, referral int, opts ...RequestOption) (*RawResponse[*SdkGetAffiliateReferralResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, referral, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// AffiliateReferralsUpdateParams contains the parameters for Update.
type AffiliateReferralsUpdateParams struct {
	Status SdkUpdateReferralStatusRequestApplicationJSONStatus `json:"status" url:"-"`
}

// Update referral status
// Move an unassigned referral through a valid review, acceptance, or rejection transition. Referrals already assigned to a payout cannot be changed independently. Requires `affiliate` and `affiliate:write`. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *AffiliateReferralService) Update(ctx context.Context, referral int, params *AffiliateReferralsUpdateParams, opts ...RequestOption) (*SdkUpdateReferralStatusResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("updateReferralStatus", false)}, opts...)
	var result SdkUpdateReferralStatusResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/v2/affiliate-referrals/%s/status", url.PathEscape(fmt.Sprint(referral))), nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkUpdateReferralStatusRequestApplicationJson\",\"properties\":{\"status\":{\"kind\":\"enum\",\"values\":[\"accepted\",\"in_review\",\"rejected\"]}},\"required\":[\"status\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *AffiliateReferralService) UpdateWithResponse(ctx context.Context, referral int, params *AffiliateReferralsUpdateParams, opts ...RequestOption) (*RawResponse[*SdkUpdateReferralStatusResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Update(ctx, referral, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
