// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestBlacklists_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v1/blacklists", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"type\":\"ASN\",\"data\":\"leo.martin@example.com\",\"description\":\"Block the address used by our launch-day load-test bot.\",\"created_at\":\"2022-12-12T12:12:12.000000Z\",\"updated_at\":\"2022-12-12T12:12:12.000000Z\",\"store_id\":1}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Blacklists().List(context.Background(), &sellapp.BlacklistsListParams{Limit: ptrInt(10)})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestBlacklists_List_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Blacklists().List(context.Background(), &sellapp.BlacklistsListParams{Limit: ptrInt(10)})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestBlacklists_Create(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v1/blacklists", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/blacklist_response.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Blacklists().Create(context.Background(), decodeTestParams[sellapp.BlacklistsCreateParams](t, "{\"type\":\"ASN\",\"data\":\"@blocked.example\",\"description\":\"Retired after the growth experiment ended.\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBlacklists_Get(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v1/blacklists/1", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/blacklist_response.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Blacklists().Get(context.Background(), 1)
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBlacklists_Update(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v1/blacklists/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/blacklist_response.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Blacklists().Update(context.Background(), 1, decodeTestParams[sellapp.BlacklistsUpdateParams](t, "{\"type\":\"ASN\",\"data\":\"@blocked-domain.example\",\"description\":\"Block purchases from this email domain.\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBlacklists_Delete(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v1/blacklists/1", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.Blacklists().Delete(context.Background(), 1)
	require.NoError(t, err)
}

func TestBlacklists_V2ListBlacklists(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/blacklists", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"type\":\"ASN\",\"data\":\"leo.martin@example.com\",\"description\":\"Block the address used by our launch-day load-test bot.\",\"created_at\":\"2022-12-12T12:12:12.000000Z\",\"updated_at\":\"2022-12-12T12:12:12.000000Z\",\"store_id\":1}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Blacklists().V2ListBlacklists(context.Background())
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestBlacklists_V2ListBlacklists_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Blacklists().V2ListBlacklists(context.Background())
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestBlacklists_V2CreateBlacklist(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/blacklists", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/blacklist_response.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Blacklists().V2CreateBlacklist(context.Background(), decodeTestParams[sellapp.BlacklistsV2CreateBlacklistParams](t, "{\"type\":\"ASN\",\"data\":\"@blocked.example\",\"description\":\"Retired after the growth experiment ended.\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBlacklists_V2GetBlacklist(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/blacklists/1", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/blacklist_response.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Blacklists().V2GetBlacklist(context.Background(), 1)
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBlacklists_V2ReplaceBlacklist(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/blacklists/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/blacklist_response.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Blacklists().V2ReplaceBlacklist(context.Background(), 1, decodeTestParams[sellapp.BlacklistsV2ReplaceBlacklistParams](t, "{\"type\":\"ASN\",\"data\":\"@blocked-domain.example\",\"description\":\"Block purchases from this email domain.\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBlacklists_V2UpdateBlacklist(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/blacklists/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/blacklist_response.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Blacklists().V2UpdateBlacklist(context.Background(), 1, decodeTestParams[sellapp.BlacklistsV2UpdateBlacklistParams](t, "{\"type\":\"ASN\",\"data\":\"@blocked-domain.example\",\"description\":\"Block purchases from this email domain.\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBlacklists_V2DeleteBlacklist(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v2/blacklists/1", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.Blacklists().V2DeleteBlacklist(context.Background(), 1)
	require.NoError(t, err)
}

func TestBlacklists_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Blacklists().List(context.Background(), &sellapp.BlacklistsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.AuthenticationError{}, iter.Err())
}

func TestBlacklists_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Blacklists().List(context.Background(), &sellapp.BlacklistsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.NotFoundError{}, iter.Err())
}

func TestBlacklists_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Blacklists().List(context.Background(), &sellapp.BlacklistsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.UnprocessableEntityError{}, iter.Err())
}
