// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestBookings_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/bookings", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Bookings().List(context.Background(), &sellapp.BookingsListParams{Limit: ptrInt(10)})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestBookings_List_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Bookings().List(context.Background(), &sellapp.BookingsListParams{Limit: ptrInt(10)})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestBookings_Search(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/bookings/search", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Bookings().Search(context.Background(), &sellapp.BookingsSearchParams{Limit: ptrInt(10)})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestBookings_Search_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Bookings().Search(context.Background(), &sellapp.BookingsSearchParams{Limit: ptrInt(10)})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestBookings_Get(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/bookings/test_booking", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_appointment_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Bookings().Get(context.Background(), "test_booking")
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBookings_Update(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/bookings/test_booking", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_appointment_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Bookings().Update(context.Background(), "test_booking", decodeTestParams[sellapp.BookingsUpdateParams](t, "{\"slot_start_at\":\"2023-01-01T00:00:00.000Z\",\"timezone\":\"test_timezone\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBookings_Cancel(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/bookings/test_booking/status", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_appointment_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Bookings().Cancel(context.Background(), "test_booking", decodeTestParams[sellapp.BookingsCancelParams](t, "{\"status\":\"cancelled\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBookings_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Bookings().List(context.Background(), &sellapp.BookingsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.AuthenticationError{}, iter.Err())
}

func TestBookings_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Bookings().List(context.Background(), &sellapp.BookingsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.NotFoundError{}, iter.Err())
}

func TestBookings_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Bookings().List(context.Background(), &sellapp.BookingsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.UnprocessableEntityError{}, iter.Err())
}
