// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestBookingsCalendarEvents_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/booking-calendar-events", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.BookingsCalendarEvents().List(context.Background(), &sellapp.BookingsCalendarEventsListParams{Limit: ptrInt(10)})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestBookingsCalendarEvents_List_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.BookingsCalendarEvents().List(context.Background(), &sellapp.BookingsCalendarEventsListParams{Limit: ptrInt(10)})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestBookingsCalendarEvents_Set(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/booking-calendar-events", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_set_booking_date_availability_response_value_201_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.BookingsCalendarEvents().Set(context.Background(), decodeTestParams[sellapp.BookingsCalendarEventsSetParams](t, "{\"product_variant_id\":1,\"dates\":[\"2023-01-01\"],\"available\":true}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestBookingsCalendarEvents_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.BookingsCalendarEvents().List(context.Background(), &sellapp.BookingsCalendarEventsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.AuthenticationError{}, iter.Err())
}

func TestBookingsCalendarEvents_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.BookingsCalendarEvents().List(context.Background(), &sellapp.BookingsCalendarEventsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.NotFoundError{}, iter.Err())
}

func TestBookingsCalendarEvents_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.BookingsCalendarEvents().List(context.Background(), &sellapp.BookingsCalendarEventsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.UnprocessableEntityError{}, iter.Err())
}
