// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"fmt"
	"net/url"
)

// BundleItemService handles BundleItems operations.
type BundleItemService struct {
	client *Client
}

// Get retrieve a bundle item
// Retrieve a specific item from a bundle by its product variant ID. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *BundleItemService) Get(ctx context.Context, bundle int, item int, opts ...RequestOption) (*SdkGetBundleItemResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getBundleItem", false)}, opts...)
	var result SdkGetBundleItemResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/bundles/%s/items/%s", url.PathEscape(fmt.Sprint(bundle)), url.PathEscape(fmt.Sprint(item))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *BundleItemService) GetWithResponse(ctx context.Context, bundle int, item int, opts ...RequestOption) (*RawResponse[*SdkGetBundleItemResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, bundle, item, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// BundleItemsListParams contains the parameters for List.
type BundleItemsListParams struct {
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
}

// List bundle items
// Retrieve a paginated list of product variants attached to a bundle. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *BundleItemService) List(ctx context.Context, bundle int, params *BundleItemsListParams, opts ...RequestOption) *Iterator[ListBundleItemsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("listBundleItems", false)}, opts...)
	return newIterator[ListBundleItemsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", fmt.Sprintf("/v2/bundles/%s/items", url.PathEscape(fmt.Sprint(bundle))), params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *BundleItemService) ListWithResponse(ctx context.Context, bundle int, params *BundleItemsListParams, opts ...RequestOption) (*RawResponse[*Iterator[ListBundleItemsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, bundle, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// BundleItemsAttachParams contains the parameters for Attach.
type BundleItemsAttachParams struct {
	Resources *AttachBundleItemsRequestApplicationJSONPropertyResources `json:"resources" url:"-"`
}

// Attach bundle items
// Attach one or more product variants to a bundle with quantities. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *BundleItemService) Attach(ctx context.Context, bundle int, params *BundleItemsAttachParams, opts ...RequestOption) (*SdkAttachBundleItemsResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("attachBundleItems", false)}, opts...)
	var result SdkAttachBundleItemsResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/v2/bundles/%s/items/attach", url.PathEscape(fmt.Sprint(bundle))), nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkAttachBundleItemsRequestApplicationJson\",\"properties\":{\"resources\":{\"kind\":\"object\",\"modelName\":\"AttachBundleItemsRequestApplicationJsonPropertyResources\",\"properties\":{},\"required\":[],\"additionalProperties\":{\"kind\":\"object\",\"modelName\":\"AttachBundleItemsRequestApplicationJsonPropertyResourcesMapValue\",\"properties\":{\"quantity\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"required\":[\"quantity\"],\"additionalProperties\":true}}},\"required\":[\"resources\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *BundleItemService) AttachWithResponse(ctx context.Context, bundle int, params *BundleItemsAttachParams, opts ...RequestOption) (*RawResponse[*SdkAttachBundleItemsResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Attach(ctx, bundle, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// BundleItemsDetachParams contains the parameters for Detach.
type BundleItemsDetachParams struct {
	Resources []int `json:"resources" url:"-"`
}

// Detach bundle items
// Detach one or more product variants from a bundle. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *BundleItemService) Detach(ctx context.Context, bundle int, params *BundleItemsDetachParams, opts ...RequestOption) error {
	opts = append([]RequestOption{withOperation("detachBundleItems", false)}, opts...)
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/v2/bundles/%s/items/detach", url.PathEscape(fmt.Sprint(bundle))), nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkDetachBundleItemsRequestApplicationJson\",\"properties\":{\"resources\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}}},\"required\":[\"resources\"],\"additionalProperties\":true}")), nil, opts)
	return err
}

func (s *BundleItemService) DetachWithResponse(ctx context.Context, bundle int, params *BundleItemsDetachParams, opts ...RequestOption) (*RawResponse[struct{}], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	if err := s.Detach(ctx, bundle, params, captureOpts...); err != nil {
		return nil, err
	}
	return rawResponse(struct{}{}, metadata), nil
}
