// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestCoupons_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v1/coupons", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":\"test_discount\",\"limit\":1,\"store_wide\":true,\"minimum_amount\":\"test_minimum_amount\",\"expires_at\":\"2026-07-03 12:15:00\",\"created_at\":\"2023-01-01T00:00:00.000Z\",\"updated_at\":\"2023-01-01T00:00:00.000Z\",\"store_id\":1,\"deleted_at\":\"2023-01-01T00:00:00.000Z\",\"maximum_discount_amount\":\"test_maximum_discount_amount\",\"products\":[1],\"product_variants\":[1]}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().List(context.Background(), &sellapp.CouponsListParams{Limit: ptrInt(10)})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestCoupons_List_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().List(context.Background(), &sellapp.CouponsListParams{Limit: ptrInt(10)})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestCoupons_Create(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v1/coupons", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_coupon_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().Create(context.Background(), decodeTestParams[sellapp.CouponsCreateParams](t, "{\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":1,\"store_wide\":true,\"products\":[1],\"product_variants\":[1],\"limit\":1,\"expires_at\":\"2023-01-01T00:00:00.000Z\",\"minimum_amount\":1}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_Get(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v1/coupons/1", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_coupon_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().Get(context.Background(), 1, &sellapp.CouponsGetParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_Replace(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v1/coupons/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_coupon_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().Replace(context.Background(), 1, decodeTestParams[sellapp.CouponsReplaceParams](t, "{\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":1,\"store_wide\":true,\"products\":[1],\"product_variants\":[1],\"limit\":1,\"expires_at\":\"2023-01-01T00:00:00.000Z\",\"minimum_amount\":1}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_Update(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v1/coupons/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_coupon_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().Update(context.Background(), 1, decodeTestParams[sellapp.CouponsUpdateParams](t, "{\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":1,\"store_wide\":true,\"products\":[1],\"product_variants\":[1],\"limit\":1,\"expires_at\":\"2023-01-01T00:00:00.000Z\",\"minimum_amount\":1}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_Delete(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v1/coupons/1", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.Coupons().Delete(context.Background(), 1, &sellapp.CouponsDeleteParams{})
	require.NoError(t, err)
}

func TestCoupons_Search(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v1/coupons/search", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":\"test_discount\",\"limit\":1,\"store_wide\":true,\"minimum_amount\":\"test_minimum_amount\",\"expires_at\":\"2026-07-03 12:15:00\",\"created_at\":\"2023-01-01T00:00:00.000Z\",\"updated_at\":\"2023-01-01T00:00:00.000Z\",\"store_id\":1,\"deleted_at\":\"2023-01-01T00:00:00.000Z\",\"maximum_discount_amount\":\"test_maximum_discount_amount\",\"products\":[1],\"product_variants\":[1]}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().Search(context.Background(), &sellapp.CouponsSearchParams{})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestCoupons_Search_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().Search(context.Background(), &sellapp.CouponsSearchParams{})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestCoupons_BatchCreate(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v1/coupons/batch", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_batch_create_coupons_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().BatchCreate(context.Background(), decodeTestParams[sellapp.CouponsBatchCreateParams](t, "{\"resources\":[{\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":1,\"store_wide\":true,\"products\":[1],\"product_variants\":[1],\"limit\":1,\"expires_at\":\"2023-01-01T00:00:00.000Z\",\"minimum_amount\":1}]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_BatchUpdate(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v1/coupons/batch", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_batch_create_coupons_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().BatchUpdate(context.Background(), decodeTestParams[sellapp.CouponsBatchUpdateParams](t, "{\"resources\":{}}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_BatchDelete(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v1/coupons/batch", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.Coupons().BatchDelete(context.Background(), decodeTestParams[sellapp.CouponsBatchDeleteParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
}

func TestCoupons_V2ListCoupons(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/coupons", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":\"test_discount\",\"limit\":1,\"store_wide\":true,\"minimum_amount\":\"test_minimum_amount\",\"expires_at\":\"2026-07-03 12:15:00\",\"created_at\":\"2023-01-01T00:00:00.000Z\",\"updated_at\":\"2023-01-01T00:00:00.000Z\",\"store_id\":1,\"deleted_at\":\"2023-01-01T00:00:00.000Z\",\"maximum_discount_amount\":\"test_maximum_discount_amount\",\"products\":[1],\"product_variants\":[1]}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().V2ListCoupons(context.Background(), &sellapp.CouponsV2ListCouponsParams{Limit: ptrInt(10)})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestCoupons_V2ListCoupons_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().V2ListCoupons(context.Background(), &sellapp.CouponsV2ListCouponsParams{Limit: ptrInt(10)})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestCoupons_V2CreateCoupon(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/coupons", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_coupon_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().V2CreateCoupon(context.Background(), decodeTestParams[sellapp.CouponsV2CreateCouponParams](t, "{\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":1,\"store_wide\":true,\"products\":[1],\"product_variants\":[1],\"limit\":1,\"expires_at\":\"2023-01-01T00:00:00.000Z\",\"minimum_amount\":1}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_V2SearchCoupons(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/coupons/search", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":\"test_discount\",\"limit\":1,\"store_wide\":true,\"minimum_amount\":\"test_minimum_amount\",\"expires_at\":\"2026-07-03 12:15:00\",\"created_at\":\"2023-01-01T00:00:00.000Z\",\"updated_at\":\"2023-01-01T00:00:00.000Z\",\"store_id\":1,\"deleted_at\":\"2023-01-01T00:00:00.000Z\",\"maximum_discount_amount\":\"test_maximum_discount_amount\",\"products\":[1],\"product_variants\":[1]}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().V2SearchCoupons(context.Background(), &sellapp.CouponsV2SearchCouponsParams{})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestCoupons_V2SearchCoupons_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().V2SearchCoupons(context.Background(), &sellapp.CouponsV2SearchCouponsParams{})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestCoupons_V2GetCoupon(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/coupons/1", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_coupon_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().V2GetCoupon(context.Background(), 1, &sellapp.CouponsV2GetCouponParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_V2ReplaceCoupon(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/coupons/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_coupon_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().V2ReplaceCoupon(context.Background(), 1, decodeTestParams[sellapp.CouponsV2ReplaceCouponParams](t, "{\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":1,\"store_wide\":true,\"products\":[1],\"product_variants\":[1],\"limit\":1,\"expires_at\":\"2023-01-01T00:00:00.000Z\",\"minimum_amount\":1}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_V2UpdateCoupon(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/coupons/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_coupon_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().V2UpdateCoupon(context.Background(), 1, decodeTestParams[sellapp.CouponsV2UpdateCouponParams](t, "{\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":1,\"store_wide\":true,\"products\":[1],\"product_variants\":[1],\"limit\":1,\"expires_at\":\"2023-01-01T00:00:00.000Z\",\"minimum_amount\":1}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_V2DeleteCoupon(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v2/coupons/1", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.Coupons().V2DeleteCoupon(context.Background(), 1, &sellapp.CouponsV2DeleteCouponParams{})
	require.NoError(t, err)
}

func TestCoupons_V2BatchCreateCoupons(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/coupons/batch", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_batch_create_coupons_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().V2BatchCreateCoupons(context.Background(), decodeTestParams[sellapp.CouponsV2BatchCreateCouponsParams](t, "{\"resources\":[{\"code\":\"test_code\",\"type\":\"PERCENTAGE\",\"discount\":1,\"store_wide\":true,\"products\":[1],\"product_variants\":[1],\"limit\":1,\"expires_at\":\"2023-01-01T00:00:00.000Z\",\"minimum_amount\":1}]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_V2BatchUpdateCoupons(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/coupons/batch", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_batch_create_coupons_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Coupons().V2BatchUpdateCoupons(context.Background(), decodeTestParams[sellapp.CouponsV2BatchUpdateCouponsParams](t, "{\"resources\":{}}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCoupons_V2BatchDeleteCoupons(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v2/coupons/batch", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.Coupons().V2BatchDeleteCoupons(context.Background(), decodeTestParams[sellapp.CouponsV2BatchDeleteCouponsParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
}

func TestCoupons_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().List(context.Background(), &sellapp.CouponsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.AuthenticationError{}, iter.Err())
}

func TestCoupons_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().List(context.Background(), &sellapp.CouponsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.NotFoundError{}, iter.Err())
}

func TestCoupons_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Coupons().List(context.Background(), &sellapp.CouponsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.UnprocessableEntityError{}, iter.Err())
}
