// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
)

// CouponService handles Coupons operations.
type CouponService struct {
	client *Client
}

// CouponsListParams contains the parameters for List.
type CouponsListParams struct {
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// List all coupons
// List your store's coupons, 15 per page by default.
func (s *CouponService) List(ctx context.Context, params *CouponsListParams, opts ...RequestOption) *Iterator[ListCouponsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("listCoupons", false)}, opts...)
	return newIterator[ListCouponsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", "/v1/coupons", params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *CouponService) ListWithResponse(ctx context.Context, params *CouponsListParams, opts ...RequestOption) (*RawResponse[*Iterator[ListCouponsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsCreateParams contains the parameters for Create.
type CouponsCreateParams struct {
	Code string                                    `json:"code" url:"-"`
	Type SdkCreateCouponRequestApplicationJSONType `json:"type" url:"-"`
	// Discount is a decimal discount value of at least 1. Percentage discounts cannot exceed 100; amount discounts use the store currency's major unit.
	Discount  interface{} `json:"discount" url:"-"`
	StoreWide bool        `json:"store_wide" url:"-"`
	// Products is product IDs the coupon applies to when store_wide is false.
	Products []int `json:"products,omitempty" url:"-"`
	// ProductVariants is optional variant restrictions. Every variant must belong to a selected product. Products without listed variants remain eligible on all variants.
	ProductVariants []int `json:"product_variants,omitempty" url:"-"`
	Limit           *int  `json:"limit,omitempty" url:"-"`
	// ExpiresAt is a future date and time, or null for no expiry.
	ExpiresAt *string `json:"expires_at,omitempty" url:"-"`
	// MinimumAmount is a decimal minimum order amount in the store currency's major unit, or null for no minimum.
	MinimumAmount *interface{} `json:"minimum_amount,omitempty" url:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for CouponsCreateParams.
func (p CouponsCreateParams) MarshalJSON() ([]byte, error) {
	type Alias CouponsCreateParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if len(p.NullFields) == 0 && p.Products == nil && p.ProductVariants == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Products != nil {
		m["products"] = p.Products
	}
	if p.ProductVariants != nil {
		m["product_variants"] = p.ProductVariants
	}
	nullable := map[string]bool{
		"limit":          true,
		"expires_at":     true,
		"minimum_amount": true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("CouponsCreateParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// Create a coupon
// Create a discount code for your store.
func (s *CouponService) Create(ctx context.Context, params *CouponsCreateParams, opts ...RequestOption) (*SdkCreateCouponResponseValue201ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("createCoupon", false)}, opts...)
	var result SdkCreateCouponResponseValue201ApplicationJSON
	_, err := s.client.request(ctx, "POST", "/v1/coupons", nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkCreateCouponRequestApplicationJson\",\"properties\":{\"code\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"type\":{\"kind\":\"enum\",\"values\":[\"PERCENTAGE\",\"AMOUNT\"]},\"discount\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]},\"store_wide\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"minItems\":1}},\"product_variants\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"limit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]}}},\"required\":[\"code\",\"type\",\"discount\",\"store_wide\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) CreateWithResponse(ctx context.Context, params *CouponsCreateParams, opts ...RequestOption) (*RawResponse[*SdkCreateCouponResponseValue201ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Create(ctx, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsGetParams contains the parameters for Get.
type CouponsGetParams struct {
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// Get retrieve a coupon
// Retrieve a coupon by its ID.
func (s *CouponService) Get(ctx context.Context, coupon int, params *CouponsGetParams, opts ...RequestOption) (*SdkGetCouponResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getCoupon", false)}, opts...)
	var result SdkGetCouponResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/coupons/%s", url.PathEscape(fmt.Sprint(coupon))), params, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) GetWithResponse(ctx context.Context, coupon int, params *CouponsGetParams, opts ...RequestOption) (*RawResponse[*SdkGetCouponResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, coupon, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsReplaceParams contains the parameters for Replace.
type CouponsReplaceParams struct {
	Code *string                                     `json:"code,omitempty" url:"-"`
	Type *SdkReplaceCouponRequestApplicationJSONType `json:"type,omitempty" url:"-"`
	// Discount is a decimal discount value of at least 1. Percentage discounts cannot exceed 100; amount discounts use the store currency's major unit.
	Discount  *interface{} `json:"discount,omitempty" url:"-"`
	StoreWide *bool        `json:"store_wide,omitempty" url:"-"`
	// Products is product IDs the coupon applies to when store_wide is false.
	Products []int `json:"products,omitempty" url:"-"`
	// ProductVariants is optional variant restrictions. Omit to preserve existing restrictions or send an empty array to allow every variant of the selected products.
	ProductVariants []int `json:"product_variants,omitempty" url:"-"`
	Limit           *int  `json:"limit,omitempty" url:"-"`
	// ExpiresAt is a future date and time, or null for no expiry.
	ExpiresAt *string `json:"expires_at,omitempty" url:"-"`
	// MinimumAmount is a decimal minimum order amount in the store currency's major unit, or null for no minimum.
	MinimumAmount *interface{} `json:"minimum_amount,omitempty" url:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for CouponsReplaceParams.
func (p CouponsReplaceParams) MarshalJSON() ([]byte, error) {
	type Alias CouponsReplaceParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if len(p.NullFields) == 0 && p.Products == nil && p.ProductVariants == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Products != nil {
		m["products"] = p.Products
	}
	if p.ProductVariants != nil {
		m["product_variants"] = p.ProductVariants
	}
	nullable := map[string]bool{
		"limit":          true,
		"expires_at":     true,
		"minimum_amount": true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("CouponsReplaceParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// Replace update a coupon
// Change a coupon's discount, limits, or eligible products.
func (s *CouponService) Replace(ctx context.Context, coupon int, params *CouponsReplaceParams, opts ...RequestOption) (*SdkReplaceCouponResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("replaceCoupon", false)}, opts...)
	var result SdkReplaceCouponResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/v1/coupons/%s", url.PathEscape(fmt.Sprint(coupon))), params, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkReplaceCouponRequestApplicationJson\",\"properties\":{\"code\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"type\":{\"kind\":\"enum\",\"values\":[\"PERCENTAGE\",\"AMOUNT\"]},\"discount\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]},\"store_wide\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"minItems\":1}},\"product_variants\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"limit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]}}},\"required\":[],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) ReplaceWithResponse(ctx context.Context, coupon int, params *CouponsReplaceParams, opts ...RequestOption) (*RawResponse[*SdkReplaceCouponResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Replace(ctx, coupon, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsUpdateParams contains the parameters for Update.
type CouponsUpdateParams struct {
	Code *string                                    `json:"code,omitempty" url:"-"`
	Type *SdkUpdateCouponRequestApplicationJSONType `json:"type,omitempty" url:"-"`
	// Discount is a decimal discount value of at least 1. Percentage discounts cannot exceed 100; amount discounts use the store currency's major unit.
	Discount  *interface{} `json:"discount,omitempty" url:"-"`
	StoreWide *bool        `json:"store_wide,omitempty" url:"-"`
	// Products is product IDs the coupon applies to when store_wide is false.
	Products []int `json:"products,omitempty" url:"-"`
	// ProductVariants is optional variant restrictions. Omit to preserve existing restrictions or send an empty array to allow every variant of the selected products.
	ProductVariants []int `json:"product_variants,omitempty" url:"-"`
	Limit           *int  `json:"limit,omitempty" url:"-"`
	// ExpiresAt is a future date and time, or null for no expiry.
	ExpiresAt *string `json:"expires_at,omitempty" url:"-"`
	// MinimumAmount is a decimal minimum order amount in the store currency's major unit, or null for no minimum.
	MinimumAmount *interface{} `json:"minimum_amount,omitempty" url:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for CouponsUpdateParams.
func (p CouponsUpdateParams) MarshalJSON() ([]byte, error) {
	type Alias CouponsUpdateParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if len(p.NullFields) == 0 && p.Products == nil && p.ProductVariants == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Products != nil {
		m["products"] = p.Products
	}
	if p.ProductVariants != nil {
		m["product_variants"] = p.ProductVariants
	}
	nullable := map[string]bool{
		"limit":          true,
		"expires_at":     true,
		"minimum_amount": true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("CouponsUpdateParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// Update a coupon
// Change a coupon's discount, limits, or eligible products.
func (s *CouponService) Update(ctx context.Context, coupon int, params *CouponsUpdateParams, opts ...RequestOption) (*SdkUpdateCouponResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("updateCoupon", false)}, opts...)
	var result SdkUpdateCouponResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/v1/coupons/%s", url.PathEscape(fmt.Sprint(coupon))), params, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkUpdateCouponRequestApplicationJson\",\"properties\":{\"code\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"type\":{\"kind\":\"enum\",\"values\":[\"PERCENTAGE\",\"AMOUNT\"]},\"discount\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]},\"store_wide\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"minItems\":1}},\"product_variants\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"limit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]}}},\"required\":[],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) UpdateWithResponse(ctx context.Context, coupon int, params *CouponsUpdateParams, opts ...RequestOption) (*RawResponse[*SdkUpdateCouponResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Update(ctx, coupon, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsDeleteParams contains the parameters for Delete.
type CouponsDeleteParams struct {
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// Delete a coupon
// Soft-delete a coupon. The returned coupon includes its deleted_at timestamp; use with_trashed or only_trashed to retrieve soft-deleted coupons later.
func (s *CouponService) Delete(ctx context.Context, coupon int, params *CouponsDeleteParams, opts ...RequestOption) error {
	opts = append([]RequestOption{withOperation("deleteCoupon", false)}, opts...)
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/v1/coupons/%s", url.PathEscape(fmt.Sprint(coupon))), params, nil, nil, opts)
	return err
}

func (s *CouponService) DeleteWithResponse(ctx context.Context, coupon int, params *CouponsDeleteParams, opts ...RequestOption) (*RawResponse[struct{}], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	if err := s.Delete(ctx, coupon, params, captureOpts...); err != nil {
		return nil, err
	}
	return rawResponse(struct{}{}, metadata), nil
}

// CouponsSearchParams contains the parameters for Search.
type CouponsSearchParams struct {
	Filters  []*SearchCouponsRequestApplicationJSONPropertyFiltersItem  `json:"filters,omitempty" url:"-"`
	Sort     []*SearchCouponsRequestApplicationJSONPropertySortItem     `json:"sort,omitempty" url:"-"`
	Search   *SearchCouponsRequestApplicationJSONPropertySearch         `json:"search,omitempty" url:"-"`
	Includes []*SearchCouponsRequestApplicationJSONPropertyIncludesItem `json:"includes,omitempty" url:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// MarshalJSON implements json.Marshaler for CouponsSearchParams.
func (p CouponsSearchParams) MarshalJSON() ([]byte, error) {
	type Alias CouponsSearchParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if p.Filters == nil && p.Sort == nil && p.Includes == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Filters != nil {
		m["filters"] = p.Filters
	}
	if p.Sort != nil {
		m["sort"] = p.Sort
	}
	if p.Includes != nil {
		m["includes"] = p.Includes
	}
	return json.Marshal(m)
}

// Search coupons
// Search coupons using JSON body filters, search terms, includes, and sort instructions.
func (s *CouponService) Search(ctx context.Context, params *CouponsSearchParams, opts ...RequestOption) *Iterator[SearchCouponsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("searchCoupons", false)}, opts...)
	return newIterator[SearchCouponsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "POST", "/v1/coupons/search", params, "after", "data", opts, nil, func() any {
		if params == nil {
			return nil
		}
		return schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkSearchCouponsRequestApplicationJson\",\"properties\":{\"filters\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchCouponsRequestApplicationJsonPropertyFiltersItem\",\"properties\":{\"field\":{\"kind\":\"primitive\",\"type\":\"string\"},\"operator\":{\"kind\":\"primitive\",\"type\":\"string\"},\"value\":{\"kind\":\"primitive\",\"type\":\"unknown\"},\"type\":{\"kind\":\"enum\",\"values\":[\"and\",\"or\"]},\"nested\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchCouponsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem\",\"properties\":{},\"required\":[],\"additionalProperties\":true}}},\"required\":[],\"additionalProperties\":true}},\"sort\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchCouponsRequestApplicationJsonPropertySortItem\",\"properties\":{\"field\":{\"kind\":\"primitive\",\"type\":\"string\"},\"direction\":{\"kind\":\"enum\",\"values\":[\"asc\",\"desc\"]}},\"required\":[\"field\"],\"additionalProperties\":true}},\"search\":{\"kind\":\"object\",\"modelName\":\"SearchCouponsRequestApplicationJsonPropertySearch\",\"properties\":{\"value\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"case_sensitive\":{\"kind\":\"primitive\",\"type\":\"boolean\"}},\"required\":[],\"additionalProperties\":true},\"includes\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchCouponsRequestApplicationJsonPropertyIncludesItem\",\"properties\":{\"relation\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"relation\"],\"additionalProperties\":true}}},\"required\":[],\"additionalProperties\":true}"))
	}())
}

func (s *CouponService) SearchWithResponse(ctx context.Context, params *CouponsSearchParams, opts ...RequestOption) (*RawResponse[*Iterator[SearchCouponsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.Search(ctx, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsBatchCreateParams contains the parameters for BatchCreate.
type CouponsBatchCreateParams struct {
	Resources []*BatchCreateCouponsRequestApplicationJSONPropertyResourcesItem `json:"resources" url:"-"`
}

// BatchCreate coupons
// Create multiple coupons in one request by sending a `resources` array.
func (s *CouponService) BatchCreate(ctx context.Context, params *CouponsBatchCreateParams, opts ...RequestOption) (*SdkBatchCreateCouponsResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("batchCreateCoupons", false)}, opts...)
	var result SdkBatchCreateCouponsResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "POST", "/v1/coupons/batch", nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkBatchCreateCouponsRequestApplicationJson\",\"properties\":{\"resources\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"BatchCreateCouponsRequestApplicationJsonPropertyResourcesItem\",\"properties\":{\"code\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"type\":{\"kind\":\"enum\",\"values\":[\"PERCENTAGE\",\"AMOUNT\"]},\"discount\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]},\"store_wide\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"minItems\":1}},\"product_variants\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"limit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]}}},\"required\":[\"code\",\"type\",\"discount\",\"store_wide\"],\"additionalProperties\":true}}},\"required\":[\"resources\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) BatchCreateWithResponse(ctx context.Context, params *CouponsBatchCreateParams, opts ...RequestOption) (*RawResponse[*SdkBatchCreateCouponsResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.BatchCreate(ctx, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsBatchUpdateParams contains the parameters for BatchUpdate.
type CouponsBatchUpdateParams struct {
	Resources *BatchUpdateCouponsRequestApplicationJSONPropertyResources `json:"resources" url:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// BatchUpdate coupons
// Update multiple coupons in one request by sending a `resources` object keyed by coupon ID.
func (s *CouponService) BatchUpdate(ctx context.Context, params *CouponsBatchUpdateParams, opts ...RequestOption) (*SdkBatchUpdateCouponsResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("batchUpdateCoupons", false)}, opts...)
	var result SdkBatchUpdateCouponsResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "PATCH", "/v1/coupons/batch", params, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkBatchUpdateCouponsRequestApplicationJson\",\"properties\":{\"resources\":{\"kind\":\"object\",\"modelName\":\"BatchUpdateCouponsRequestApplicationJsonPropertyResources\",\"properties\":{},\"required\":[],\"additionalProperties\":{\"kind\":\"object\",\"modelName\":\"BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValue\",\"properties\":{\"code\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"type\":{\"kind\":\"enum\",\"values\":[\"PERCENTAGE\",\"AMOUNT\"]},\"discount\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]},\"store_wide\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"minItems\":1}},\"product_variants\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"limit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]}}},\"required\":[],\"additionalProperties\":true}}},\"required\":[\"resources\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) BatchUpdateWithResponse(ctx context.Context, params *CouponsBatchUpdateParams, opts ...RequestOption) (*RawResponse[*SdkBatchUpdateCouponsResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.BatchUpdate(ctx, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsBatchDeleteParams contains the parameters for BatchDelete.
type CouponsBatchDeleteParams struct {
	Resources []int `json:"resources" url:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// BatchDelete coupons
// Soft-delete multiple coupons by sending their IDs in `resources`.
func (s *CouponService) BatchDelete(ctx context.Context, params *CouponsBatchDeleteParams, opts ...RequestOption) error {
	opts = append([]RequestOption{withOperation("batchDeleteCoupons", false)}, opts...)
	_, err := s.client.request(ctx, "DELETE", "/v1/coupons/batch", params, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkBatchDeleteCouponsRequestApplicationJson\",\"properties\":{\"resources\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}}},\"required\":[\"resources\"],\"additionalProperties\":true}")), nil, opts)
	return err
}

func (s *CouponService) BatchDeleteWithResponse(ctx context.Context, params *CouponsBatchDeleteParams, opts ...RequestOption) (*RawResponse[struct{}], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	if err := s.BatchDelete(ctx, params, captureOpts...); err != nil {
		return nil, err
	}
	return rawResponse(struct{}{}, metadata), nil
}

// CouponsV2ListCouponsParams contains the parameters for V2ListCoupons.
type CouponsV2ListCouponsParams struct {
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// V2ListCoupons list all coupons
// List your store's coupons, 15 per page by default. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CouponService) V2ListCoupons(ctx context.Context, params *CouponsV2ListCouponsParams, opts ...RequestOption) *Iterator[V2ListCouponsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("v2ListCoupons", false)}, opts...)
	return newIterator[V2ListCouponsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", "/v2/coupons", params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *CouponService) V2ListCouponsWithResponse(ctx context.Context, params *CouponsV2ListCouponsParams, opts ...RequestOption) (*RawResponse[*Iterator[V2ListCouponsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.V2ListCoupons(ctx, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsV2CreateCouponParams contains the parameters for V2CreateCoupon.
type CouponsV2CreateCouponParams struct {
	Code string                                      `json:"code" url:"-"`
	Type SdkV2CreateCouponRequestApplicationJSONType `json:"type" url:"-"`
	// Discount is a decimal discount value of at least 1. Percentage discounts cannot exceed 100; amount discounts use the store currency's major unit.
	Discount  interface{} `json:"discount" url:"-"`
	StoreWide bool        `json:"store_wide" url:"-"`
	// Products is product IDs the coupon applies to when store_wide is false.
	Products []int `json:"products,omitempty" url:"-"`
	// ProductVariants is optional variant restrictions. Every variant must belong to a selected product. Products without listed variants remain eligible on all variants.
	ProductVariants []int `json:"product_variants,omitempty" url:"-"`
	Limit           *int  `json:"limit,omitempty" url:"-"`
	// ExpiresAt is a future date and time, or null for no expiry.
	ExpiresAt *string `json:"expires_at,omitempty" url:"-"`
	// MinimumAmount is a decimal minimum order amount in the store currency's major unit, or null for no minimum.
	MinimumAmount *interface{} `json:"minimum_amount,omitempty" url:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for CouponsV2CreateCouponParams.
func (p CouponsV2CreateCouponParams) MarshalJSON() ([]byte, error) {
	type Alias CouponsV2CreateCouponParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if len(p.NullFields) == 0 && p.Products == nil && p.ProductVariants == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Products != nil {
		m["products"] = p.Products
	}
	if p.ProductVariants != nil {
		m["product_variants"] = p.ProductVariants
	}
	nullable := map[string]bool{
		"limit":          true,
		"expires_at":     true,
		"minimum_amount": true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("CouponsV2CreateCouponParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// V2CreateCoupon create a coupon
// Create a discount code for your store. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CouponService) V2CreateCoupon(ctx context.Context, params *CouponsV2CreateCouponParams, opts ...RequestOption) (*SdkV2CreateCouponResponseValue201ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("v2CreateCoupon", true)}, opts...)
	var result SdkV2CreateCouponResponseValue201ApplicationJSON
	_, err := s.client.request(ctx, "POST", "/v2/coupons", nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkV2CreateCouponRequestApplicationJson\",\"properties\":{\"code\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"type\":{\"kind\":\"enum\",\"values\":[\"PERCENTAGE\",\"AMOUNT\"]},\"discount\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]},\"store_wide\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"minItems\":1}},\"product_variants\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"limit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]}}},\"required\":[\"code\",\"type\",\"discount\",\"store_wide\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) V2CreateCouponWithResponse(ctx context.Context, params *CouponsV2CreateCouponParams, opts ...RequestOption) (*RawResponse[*SdkV2CreateCouponResponseValue201ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.V2CreateCoupon(ctx, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsV2SearchCouponsParams contains the parameters for V2SearchCoupons.
type CouponsV2SearchCouponsParams struct {
	Filters  []*V2SearchCouponsRequestApplicationJSONPropertyFiltersItem  `json:"filters,omitempty" url:"-"`
	Sort     []*V2SearchCouponsRequestApplicationJSONPropertySortItem     `json:"sort,omitempty" url:"-"`
	Search   *V2SearchCouponsRequestApplicationJSONPropertySearch         `json:"search,omitempty" url:"-"`
	Includes []*V2SearchCouponsRequestApplicationJSONPropertyIncludesItem `json:"includes,omitempty" url:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// MarshalJSON implements json.Marshaler for CouponsV2SearchCouponsParams.
func (p CouponsV2SearchCouponsParams) MarshalJSON() ([]byte, error) {
	type Alias CouponsV2SearchCouponsParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if p.Filters == nil && p.Sort == nil && p.Includes == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Filters != nil {
		m["filters"] = p.Filters
	}
	if p.Sort != nil {
		m["sort"] = p.Sort
	}
	if p.Includes != nil {
		m["includes"] = p.Includes
	}
	return json.Marshal(m)
}

// V2SearchCoupons search coupons
// Search coupons using JSON body filters, search terms, includes, and sort instructions. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CouponService) V2SearchCoupons(ctx context.Context, params *CouponsV2SearchCouponsParams, opts ...RequestOption) *Iterator[V2SearchCouponsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("v2SearchCoupons", true)}, opts...)
	return newIterator[V2SearchCouponsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "POST", "/v2/coupons/search", params, "after", "data", opts, nil, func() any {
		if params == nil {
			return nil
		}
		return schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkV2SearchCouponsRequestApplicationJson\",\"properties\":{\"filters\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"V2SearchCouponsRequestApplicationJsonPropertyFiltersItem\",\"properties\":{\"field\":{\"kind\":\"primitive\",\"type\":\"string\"},\"operator\":{\"kind\":\"primitive\",\"type\":\"string\"},\"value\":{\"kind\":\"primitive\",\"type\":\"unknown\"},\"type\":{\"kind\":\"enum\",\"values\":[\"and\",\"or\"]},\"nested\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"V2SearchCouponsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem\",\"properties\":{},\"required\":[],\"additionalProperties\":true}}},\"required\":[],\"additionalProperties\":true}},\"sort\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"V2SearchCouponsRequestApplicationJsonPropertySortItem\",\"properties\":{\"field\":{\"kind\":\"primitive\",\"type\":\"string\"},\"direction\":{\"kind\":\"enum\",\"values\":[\"asc\",\"desc\"]}},\"required\":[\"field\"],\"additionalProperties\":true}},\"search\":{\"kind\":\"object\",\"modelName\":\"V2SearchCouponsRequestApplicationJsonPropertySearch\",\"properties\":{\"value\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"case_sensitive\":{\"kind\":\"primitive\",\"type\":\"boolean\"}},\"required\":[],\"additionalProperties\":true},\"includes\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"V2SearchCouponsRequestApplicationJsonPropertyIncludesItem\",\"properties\":{\"relation\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"relation\"],\"additionalProperties\":true}}},\"required\":[],\"additionalProperties\":true}"))
	}())
}

func (s *CouponService) V2SearchCouponsWithResponse(ctx context.Context, params *CouponsV2SearchCouponsParams, opts ...RequestOption) (*RawResponse[*Iterator[V2SearchCouponsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.V2SearchCoupons(ctx, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsV2GetCouponParams contains the parameters for V2GetCoupon.
type CouponsV2GetCouponParams struct {
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// V2GetCoupon retrieve a coupon
// Retrieve a coupon by its ID. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CouponService) V2GetCoupon(ctx context.Context, coupon int, params *CouponsV2GetCouponParams, opts ...RequestOption) (*SdkV2GetCouponResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("v2GetCoupon", false)}, opts...)
	var result SdkV2GetCouponResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/coupons/%s", url.PathEscape(fmt.Sprint(coupon))), params, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) V2GetCouponWithResponse(ctx context.Context, coupon int, params *CouponsV2GetCouponParams, opts ...RequestOption) (*RawResponse[*SdkV2GetCouponResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.V2GetCoupon(ctx, coupon, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsV2ReplaceCouponParams contains the parameters for V2ReplaceCoupon.
type CouponsV2ReplaceCouponParams struct {
	Code *string                                       `json:"code,omitempty" url:"-"`
	Type *SdkV2ReplaceCouponRequestApplicationJSONType `json:"type,omitempty" url:"-"`
	// Discount is a decimal discount value of at least 1. Percentage discounts cannot exceed 100; amount discounts use the store currency's major unit.
	Discount  *interface{} `json:"discount,omitempty" url:"-"`
	StoreWide *bool        `json:"store_wide,omitempty" url:"-"`
	// Products is product IDs the coupon applies to when store_wide is false.
	Products []int `json:"products,omitempty" url:"-"`
	// ProductVariants is optional variant restrictions. Omit to preserve existing restrictions or send an empty array to allow every variant of the selected products.
	ProductVariants []int `json:"product_variants,omitempty" url:"-"`
	Limit           *int  `json:"limit,omitempty" url:"-"`
	// ExpiresAt is a future date and time, or null for no expiry.
	ExpiresAt *string `json:"expires_at,omitempty" url:"-"`
	// MinimumAmount is a decimal minimum order amount in the store currency's major unit, or null for no minimum.
	MinimumAmount *interface{} `json:"minimum_amount,omitempty" url:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for CouponsV2ReplaceCouponParams.
func (p CouponsV2ReplaceCouponParams) MarshalJSON() ([]byte, error) {
	type Alias CouponsV2ReplaceCouponParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if len(p.NullFields) == 0 && p.Products == nil && p.ProductVariants == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Products != nil {
		m["products"] = p.Products
	}
	if p.ProductVariants != nil {
		m["product_variants"] = p.ProductVariants
	}
	nullable := map[string]bool{
		"limit":          true,
		"expires_at":     true,
		"minimum_amount": true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("CouponsV2ReplaceCouponParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// V2ReplaceCoupon update a coupon
// Change a coupon's discount, limits, or eligible products. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CouponService) V2ReplaceCoupon(ctx context.Context, coupon int, params *CouponsV2ReplaceCouponParams, opts ...RequestOption) (*SdkV2ReplaceCouponResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("v2ReplaceCoupon", false)}, opts...)
	var result SdkV2ReplaceCouponResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/v2/coupons/%s", url.PathEscape(fmt.Sprint(coupon))), params, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkV2ReplaceCouponRequestApplicationJson\",\"properties\":{\"code\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"type\":{\"kind\":\"enum\",\"values\":[\"PERCENTAGE\",\"AMOUNT\"]},\"discount\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]},\"store_wide\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"minItems\":1}},\"product_variants\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"limit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]}}},\"required\":[],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) V2ReplaceCouponWithResponse(ctx context.Context, coupon int, params *CouponsV2ReplaceCouponParams, opts ...RequestOption) (*RawResponse[*SdkV2ReplaceCouponResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.V2ReplaceCoupon(ctx, coupon, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsV2UpdateCouponParams contains the parameters for V2UpdateCoupon.
type CouponsV2UpdateCouponParams struct {
	Code *string                                      `json:"code,omitempty" url:"-"`
	Type *SdkV2UpdateCouponRequestApplicationJSONType `json:"type,omitempty" url:"-"`
	// Discount is a decimal discount value of at least 1. Percentage discounts cannot exceed 100; amount discounts use the store currency's major unit.
	Discount  *interface{} `json:"discount,omitempty" url:"-"`
	StoreWide *bool        `json:"store_wide,omitempty" url:"-"`
	// Products is product IDs the coupon applies to when store_wide is false.
	Products []int `json:"products,omitempty" url:"-"`
	// ProductVariants is optional variant restrictions. Omit to preserve existing restrictions or send an empty array to allow every variant of the selected products.
	ProductVariants []int `json:"product_variants,omitempty" url:"-"`
	Limit           *int  `json:"limit,omitempty" url:"-"`
	// ExpiresAt is a future date and time, or null for no expiry.
	ExpiresAt *string `json:"expires_at,omitempty" url:"-"`
	// MinimumAmount is a decimal minimum order amount in the store currency's major unit, or null for no minimum.
	MinimumAmount *interface{} `json:"minimum_amount,omitempty" url:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for CouponsV2UpdateCouponParams.
func (p CouponsV2UpdateCouponParams) MarshalJSON() ([]byte, error) {
	type Alias CouponsV2UpdateCouponParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if len(p.NullFields) == 0 && p.Products == nil && p.ProductVariants == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Products != nil {
		m["products"] = p.Products
	}
	if p.ProductVariants != nil {
		m["product_variants"] = p.ProductVariants
	}
	nullable := map[string]bool{
		"limit":          true,
		"expires_at":     true,
		"minimum_amount": true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("CouponsV2UpdateCouponParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// V2UpdateCoupon update a coupon
// Change a coupon's discount, limits, or eligible products. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CouponService) V2UpdateCoupon(ctx context.Context, coupon int, params *CouponsV2UpdateCouponParams, opts ...RequestOption) (*SdkV2UpdateCouponResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("v2UpdateCoupon", false)}, opts...)
	var result SdkV2UpdateCouponResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/v2/coupons/%s", url.PathEscape(fmt.Sprint(coupon))), params, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkV2UpdateCouponRequestApplicationJson\",\"properties\":{\"code\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"type\":{\"kind\":\"enum\",\"values\":[\"PERCENTAGE\",\"AMOUNT\"]},\"discount\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]},\"store_wide\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"minItems\":1}},\"product_variants\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"limit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]}}},\"required\":[],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) V2UpdateCouponWithResponse(ctx context.Context, coupon int, params *CouponsV2UpdateCouponParams, opts ...RequestOption) (*RawResponse[*SdkV2UpdateCouponResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.V2UpdateCoupon(ctx, coupon, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsV2DeleteCouponParams contains the parameters for V2DeleteCoupon.
type CouponsV2DeleteCouponParams struct {
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// V2DeleteCoupon delete a coupon
// Soft-delete a coupon. The returned coupon includes its deleted_at timestamp; use with_trashed or only_trashed to retrieve soft-deleted coupons later. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CouponService) V2DeleteCoupon(ctx context.Context, coupon int, params *CouponsV2DeleteCouponParams, opts ...RequestOption) error {
	opts = append([]RequestOption{withOperation("v2DeleteCoupon", false)}, opts...)
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/v2/coupons/%s", url.PathEscape(fmt.Sprint(coupon))), params, nil, nil, opts)
	return err
}

func (s *CouponService) V2DeleteCouponWithResponse(ctx context.Context, coupon int, params *CouponsV2DeleteCouponParams, opts ...RequestOption) (*RawResponse[struct{}], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	if err := s.V2DeleteCoupon(ctx, coupon, params, captureOpts...); err != nil {
		return nil, err
	}
	return rawResponse(struct{}{}, metadata), nil
}

// CouponsV2BatchCreateCouponsParams contains the parameters for V2BatchCreateCoupons.
type CouponsV2BatchCreateCouponsParams struct {
	Resources []*V2BatchCreateCouponsRequestApplicationJSONPropertyResourcesItem `json:"resources" url:"-"`
}

// V2BatchCreateCoupons batch create coupons
// Create multiple coupons in one request by sending a `resources` array. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CouponService) V2BatchCreateCoupons(ctx context.Context, params *CouponsV2BatchCreateCouponsParams, opts ...RequestOption) (*SdkV2BatchCreateCouponsResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("v2BatchCreateCoupons", true)}, opts...)
	var result SdkV2BatchCreateCouponsResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "POST", "/v2/coupons/batch", nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkV2BatchCreateCouponsRequestApplicationJson\",\"properties\":{\"resources\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"V2BatchCreateCouponsRequestApplicationJsonPropertyResourcesItem\",\"properties\":{\"code\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"type\":{\"kind\":\"enum\",\"values\":[\"PERCENTAGE\",\"AMOUNT\"]},\"discount\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]},\"store_wide\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"minItems\":1}},\"product_variants\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"limit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]}}},\"required\":[\"code\",\"type\",\"discount\",\"store_wide\"],\"additionalProperties\":true}}},\"required\":[\"resources\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) V2BatchCreateCouponsWithResponse(ctx context.Context, params *CouponsV2BatchCreateCouponsParams, opts ...RequestOption) (*RawResponse[*SdkV2BatchCreateCouponsResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.V2BatchCreateCoupons(ctx, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsV2BatchUpdateCouponsParams contains the parameters for V2BatchUpdateCoupons.
type CouponsV2BatchUpdateCouponsParams struct {
	Resources *V2BatchUpdateCouponsRequestApplicationJSONPropertyResources `json:"resources" url:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// V2BatchUpdateCoupons batch update coupons
// Update multiple coupons in one request by sending a `resources` object keyed by coupon ID. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CouponService) V2BatchUpdateCoupons(ctx context.Context, params *CouponsV2BatchUpdateCouponsParams, opts ...RequestOption) (*SdkV2BatchUpdateCouponsResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("v2BatchUpdateCoupons", true)}, opts...)
	var result SdkV2BatchUpdateCouponsResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "PATCH", "/v2/coupons/batch", params, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkV2BatchUpdateCouponsRequestApplicationJson\",\"properties\":{\"resources\":{\"kind\":\"object\",\"modelName\":\"V2BatchUpdateCouponsRequestApplicationJsonPropertyResources\",\"properties\":{},\"required\":[],\"additionalProperties\":{\"kind\":\"object\",\"modelName\":\"V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValue\",\"properties\":{\"code\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"type\":{\"kind\":\"enum\",\"values\":[\"PERCENTAGE\",\"AMOUNT\"]},\"discount\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]},\"store_wide\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"minItems\":1}},\"product_variants\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"limit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"union\",\"variants\":[{\"kind\":\"primitive\",\"type\":\"number\",\"constraints\":{\"minimum\":1,\"maxLength\":255}},{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minimum\":1,\"maxLength\":255}}]}}},\"required\":[],\"additionalProperties\":true}}},\"required\":[\"resources\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CouponService) V2BatchUpdateCouponsWithResponse(ctx context.Context, params *CouponsV2BatchUpdateCouponsParams, opts ...RequestOption) (*RawResponse[*SdkV2BatchUpdateCouponsResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.V2BatchUpdateCoupons(ctx, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// CouponsV2BatchDeleteCouponsParams contains the parameters for V2BatchDeleteCoupons.
type CouponsV2BatchDeleteCouponsParams struct {
	Resources []int `json:"resources" url:"-"`
	// WithTrashed is include soft-deleted resources in the result.
	// Defaults to false.
	WithTrashed *bool `url:"with_trashed,omitempty" json:"-"`
	// OnlyTrashed is return only soft-deleted resources. Ignored when with_trashed is true.
	// Defaults to false.
	OnlyTrashed *bool `url:"only_trashed,omitempty" json:"-"`
}

// V2BatchDeleteCoupons batch delete coupons
// Soft-delete multiple coupons by sending their IDs in `resources`. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CouponService) V2BatchDeleteCoupons(ctx context.Context, params *CouponsV2BatchDeleteCouponsParams, opts ...RequestOption) error {
	opts = append([]RequestOption{withOperation("v2BatchDeleteCoupons", false)}, opts...)
	_, err := s.client.request(ctx, "DELETE", "/v2/coupons/batch", params, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkV2BatchDeleteCouponsRequestApplicationJson\",\"properties\":{\"resources\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"}}},\"required\":[\"resources\"],\"additionalProperties\":true}")), nil, opts)
	return err
}

func (s *CouponService) V2BatchDeleteCouponsWithResponse(ctx context.Context, params *CouponsV2BatchDeleteCouponsParams, opts ...RequestOption) (*RawResponse[struct{}], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	if err := s.V2BatchDeleteCoupons(ctx, params, captureOpts...); err != nil {
		return nil, err
	}
	return rawResponse(struct{}{}, metadata), nil
}
