// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"encoding/json"
	"fmt"
)

// CreditService handles Credits operations.
type CreditService struct {
	client *Client
}

// CreditsRecordParams contains the parameters for Record.
type CreditsRecordParams struct {
	CustomerID int                                                  `json:"customer_id" url:"-"`
	ProductID  int                                                  `json:"product_id" url:"-"`
	Kind       SdkRecordCreditTransactionRequestApplicationJSONKind `json:"kind" url:"-"`
	// AmountUnits is the signed amount of credit units. Must not be zero.
	AmountUnits    int                                                            `json:"amount_units" url:"-"`
	IdempotencyKey string                                                         `json:"idempotency_key" url:"-"`
	Reason         *string                                                        `json:"reason,omitempty" url:"-"`
	SourceType     *string                                                        `json:"source_type,omitempty" url:"-"`
	SourceID       *string                                                        `json:"source_id,omitempty" url:"-"`
	Metadata       *RecordCreditTransactionRequestApplicationJSONPropertyMetadata `json:"metadata,omitempty" url:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for CreditsRecordParams.
func (p CreditsRecordParams) MarshalJSON() ([]byte, error) {
	type Alias CreditsRecordParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if len(p.NullFields) == 0 {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	nullable := map[string]bool{
		"reason":      true,
		"source_type": true,
		"source_id":   true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("CreditsRecordParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// Record a credit transaction
// Atomically grant, consume, or administratively adjust integer credit units. Reusing the same idempotency key with the same transaction is a no-op; conflicting reuse is rejected. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CreditService) Record(ctx context.Context, params *CreditsRecordParams, opts ...RequestOption) (*SdkRecordCreditTransactionResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("recordCreditTransaction", false)}, opts...)
	var result SdkRecordCreditTransactionResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "POST", "/v2/credit-transactions", nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkRecordCreditTransactionRequestApplicationJson\",\"properties\":{\"customer_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"product_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"kind\":{\"kind\":\"enum\",\"values\":[\"grant\",\"consumption\",\"adjustment\"]},\"amount_units\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"idempotency_key\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minLength\":1,\"maxLength\":128}},\"reason\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":1000}}},\"source_type\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":64}}},\"source_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":128}}},\"metadata\":{\"kind\":\"object\",\"modelName\":\"RecordCreditTransactionRequestApplicationJsonPropertyMetadata\",\"properties\":{},\"required\":[],\"additionalProperties\":true}},\"required\":[\"customer_id\",\"product_id\",\"kind\",\"amount_units\",\"idempotency_key\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CreditService) RecordWithResponse(ctx context.Context, params *CreditsRecordParams, opts ...RequestOption) (*RawResponse[*SdkRecordCreditTransactionResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Record(ctx, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
