// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestCredits_Record(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/credit-transactions", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_record_credit_transaction_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Credits().Record(context.Background(), decodeTestParams[sellapp.CreditsRecordParams](t, "{\"customer_id\":1,\"product_id\":1,\"kind\":\"grant\",\"amount_units\":1,\"idempotency_key\":\"idempotency_key_01234\",\"reason\":\"test_reason\",\"source_type\":\"test_source_type\",\"source_id\":\"source_id_01234\",\"metadata\":{}}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestCredits_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.Credits().Record(context.Background(), decodeTestParams[sellapp.CreditsRecordParams](t, "{\"customer_id\":1,\"product_id\":1,\"kind\":\"grant\",\"amount_units\":1,\"idempotency_key\":\"idempotency_key_01234\",\"reason\":\"test_reason\",\"source_type\":\"test_source_type\",\"source_id\":\"source_id_01234\",\"metadata\":{}}"))
	require.IsType(t, &sellapp.AuthenticationError{}, err)
}

func TestCredits_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.Credits().Record(context.Background(), decodeTestParams[sellapp.CreditsRecordParams](t, "{\"customer_id\":1,\"product_id\":1,\"kind\":\"grant\",\"amount_units\":1,\"idempotency_key\":\"idempotency_key_01234\",\"reason\":\"test_reason\",\"source_type\":\"test_source_type\",\"source_id\":\"source_id_01234\",\"metadata\":{}}"))
	require.IsType(t, &sellapp.NotFoundError{}, err)
}

func TestCredits_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.Credits().Record(context.Background(), decodeTestParams[sellapp.CreditsRecordParams](t, "{\"customer_id\":1,\"product_id\":1,\"kind\":\"grant\",\"amount_units\":1,\"idempotency_key\":\"idempotency_key_01234\",\"reason\":\"test_reason\",\"source_type\":\"test_source_type\",\"source_id\":\"source_id_01234\",\"metadata\":{}}"))
	require.IsType(t, &sellapp.UnprocessableEntityError{}, err)
}
