// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"fmt"
	"net/url"
)

// CreditsBalanceService handles CreditsBalances operations.
type CreditsBalanceService struct {
	client *Client
}

// CreditsBalancesListParams contains the parameters for List.
type CreditsBalancesListParams struct {
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
	// Pagination is set to false to return at most 100 matching items in one data array without pagination links or metadata.
	// Defaults to true.
	Pagination *bool `url:"pagination,omitempty" json:"-"`
	// CustomerID is filter by a store customer ID.
	CustomerID *int `url:"customer_id,omitempty" json:"-"`
	// ProductID is filter by a credits product ID.
	ProductID *int `url:"product_id,omitempty" json:"-"`
}

// List credit balances
// List store-scoped customer balances for dedicated credits products. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CreditsBalanceService) List(ctx context.Context, params *CreditsBalancesListParams, opts ...RequestOption) *Iterator[SdkListCreditBalancesResponseValue200ApplicationJSON] {
	opts = append([]RequestOption{withOperation("listCreditBalances", false)}, opts...)
	return newIterator[SdkListCreditBalancesResponseValue200ApplicationJSON](ctx, s.client, "GET", "/v2/credit-balances", params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *CreditsBalanceService) ListWithResponse(ctx context.Context, params *CreditsBalancesListParams, opts ...RequestOption) (*RawResponse[*Iterator[SdkListCreditBalancesResponseValue200ApplicationJSON]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Get retrieve a credit balance
// Retrieve one customer and credits-product balance with up to 100 recent ledger entries. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *CreditsBalanceService) Get(ctx context.Context, customer int, creditProduct int, opts ...RequestOption) (*SdkGetCreditBalanceResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getCreditBalance", false)}, opts...)
	var result SdkGetCreditBalanceResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/credit-balances/%s/%s", url.PathEscape(fmt.Sprint(customer)), url.PathEscape(fmt.Sprint(creditProduct))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *CreditsBalanceService) GetWithResponse(ctx context.Context, customer int, creditProduct int, opts ...RequestOption) (*RawResponse[*SdkGetCreditBalanceResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, customer, creditProduct, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
