// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"fmt"
	"net/url"
)

// EntitlementService handles Entitlements operations.
type EntitlementService struct {
	client *Client
}

// ListCustomerEntitlements
// Unified access without raw keys, serials, files, dynamic payloads, or seller-only metadata. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *EntitlementService) ListCustomerEntitlements(ctx context.Context, customer int, opts ...RequestOption) (*SdkListCustomerEntitlementsResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("listCustomerEntitlements", false)}, opts...)
	var result SdkListCustomerEntitlementsResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/customers/%s/entitlements", url.PathEscape(fmt.Sprint(customer))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *EntitlementService) ListCustomerEntitlementsWithResponse(ctx context.Context, customer int, opts ...RequestOption) (*RawResponse[*SdkListCustomerEntitlementsResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.ListCustomerEntitlements(ctx, customer, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// ListCustomerEntitlementsByExternalID list customer entitlements
// Unified access without raw keys, serials, files, dynamic payloads, or seller-only metadata. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *EntitlementService) ListCustomerEntitlementsByExternalID(ctx context.Context, externalID string, opts ...RequestOption) (*SdkListCustomerEntitlementsResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("listCustomerEntitlementsByExternalId", false)}, opts...)
	var result SdkListCustomerEntitlementsResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/customers/external/%s/entitlements", url.PathEscape(fmt.Sprint(externalID))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *EntitlementService) ListCustomerEntitlementsByExternalIDWithResponse(ctx context.Context, externalID string, opts ...RequestOption) (*RawResponse[*SdkListCustomerEntitlementsResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.ListCustomerEntitlementsByExternalID(ctx, externalID, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
