// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestGroupsProducts_Add(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/groups/1/products/attach", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_add_products_to_group_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.GroupsProducts().Add(context.Background(), 1, decodeTestParams[sellapp.GroupsProductsAddParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestGroupsProducts_Remove(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v2/groups/1/products/detach", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.GroupsProducts().Remove(context.Background(), 1, decodeTestParams[sellapp.GroupsProductsRemoveParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
}

func TestGroupsProducts_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/groups/1/products", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"title\":\"test_title\",\"slug\":\"test_slug\",\"description\":\"test_description\",\"images\":[{\"path\":\"test_path\",\"metadata\":{\"size\":1,\"filename\":\"Test\",\"extension\":\"test_extension\",\"mime_type\":\"test_mime_type\"}}],\"order\":1,\"visibility\":\"test_visibility\",\"delivery_text\":\"test_delivery_text\",\"additional_information\":[\"test_additional_information\"],\"other_settings\":{\"faq\":[{\"question\":\"test_question\",\"answer\":\"test_answer\"}],\"video_url\":\"video_url_01234\",\"redirect_url\":\"https://example.com\",\"product_title\":\"test_product_title\",\"product_description\":\"test_product_description\"},\"deleted_at\":\"2023-01-01T00:00:00.000Z\",\"created_at\":\"2023-01-01T00:00:00.000Z\",\"updated_at\":\"2023-01-01T00:00:00.000Z\",\"store_id\":1,\"section_id\":1,\"section_order\":1,\"is_discoverable\":true,\"pivot\":{\"group_id\":1,\"listing_id\":1,\"order\":1},\"default_price\":{\"price\":\"test_price\",\"currency\":\"test_currency\"}}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.GroupsProducts().List(context.Background(), 1, &sellapp.GroupsProductsListParams{Limit: ptrInt(10)})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestGroupsProducts_List_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.GroupsProducts().List(context.Background(), 1, &sellapp.GroupsProductsListParams{Limit: ptrInt(10)})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestGroupsProducts_Replace(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/groups/1/products", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_group_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.GroupsProducts().Replace(context.Background(), 1, decodeTestParams[sellapp.GroupsProductsReplaceParams](t, "{\"product_ids\":[1]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestGroupsProducts_Get(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/groups/1/products/1", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_product_within_group_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.GroupsProducts().Get(context.Background(), 1, 1)
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestGroupsProducts_Search(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/groups/1/products/search", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"title\":\"test_title\",\"slug\":\"test_slug\",\"description\":\"test_description\",\"images\":[{\"path\":\"test_path\",\"metadata\":{\"size\":1,\"filename\":\"Test\",\"extension\":\"test_extension\",\"mime_type\":\"test_mime_type\"}}],\"order\":1,\"visibility\":\"test_visibility\",\"delivery_text\":\"test_delivery_text\",\"additional_information\":[\"test_additional_information\"],\"other_settings\":{\"faq\":[{\"question\":\"test_question\",\"answer\":\"test_answer\"}],\"video_url\":\"video_url_01234\",\"redirect_url\":\"https://example.com\",\"product_title\":\"test_product_title\",\"product_description\":\"test_product_description\"},\"deleted_at\":\"2023-01-01T00:00:00.000Z\",\"created_at\":\"2023-01-01T00:00:00.000Z\",\"updated_at\":\"2023-01-01T00:00:00.000Z\",\"store_id\":1,\"section_id\":1,\"section_order\":1,\"is_discoverable\":true,\"pivot\":{\"group_id\":1,\"listing_id\":1,\"order\":1},\"default_price\":{\"price\":\"test_price\",\"currency\":\"test_currency\"}}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.GroupsProducts().Search(context.Background(), 1, &sellapp.GroupsProductsSearchParams{})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestGroupsProducts_Search_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.GroupsProducts().Search(context.Background(), 1, &sellapp.GroupsProductsSearchParams{})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestGroupsProducts_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.GroupsProducts().Add(context.Background(), 1, decodeTestParams[sellapp.GroupsProductsAddParams](t, "{\"resources\":[1]}"))
	require.IsType(t, &sellapp.AuthenticationError{}, err)
}

func TestGroupsProducts_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.GroupsProducts().Add(context.Background(), 1, decodeTestParams[sellapp.GroupsProductsAddParams](t, "{\"resources\":[1]}"))
	require.IsType(t, &sellapp.NotFoundError{}, err)
}

func TestGroupsProducts_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.GroupsProducts().Add(context.Background(), 1, decodeTestParams[sellapp.GroupsProductsAddParams](t, "{\"resources\":[1]}"))
	require.IsType(t, &sellapp.UnprocessableEntityError{}, err)
}
