// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
)

// LicenseInstanceService handles LicenseInstances operations.
type LicenseInstanceService struct {
	client *Client
}

// LicenseInstancesListParams contains the parameters for List.
type LicenseInstancesListParams struct {
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
}

// List all license instances
// Retrieve a paginated list of license instances across your store. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *LicenseInstanceService) List(ctx context.Context, params *LicenseInstancesListParams, opts ...RequestOption) *Iterator[ListLicenseInstancesResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("listLicenseInstances", false)}, opts...)
	return newIterator[ListLicenseInstancesResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", "/v2/license-key-instances", params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *LicenseInstanceService) ListWithResponse(ctx context.Context, params *LicenseInstancesListParams, opts ...RequestOption) (*RawResponse[*Iterator[ListLicenseInstancesResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
