// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"fmt"
	"net/url"
)

// LicensesInstanceService handles LicensesInstances operations.
type LicensesInstanceService struct {
	client *Client
}

// LicensesInstancesListParams contains the parameters for List.
type LicensesInstancesListParams struct {
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
}

// List license instances
// List the activations for a license key, one page at a time. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *LicensesInstanceService) List(ctx context.Context, licenseKey int, params *LicensesInstancesListParams, opts ...RequestOption) *Iterator[ListLicenseKeyInstancesResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("listLicenseKeyInstances", false)}, opts...)
	return newIterator[ListLicenseKeyInstancesResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", fmt.Sprintf("/v2/license-keys/%s/instances", url.PathEscape(fmt.Sprint(licenseKey))), params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *LicensesInstanceService) ListWithResponse(ctx context.Context, licenseKey int, params *LicensesInstancesListParams, opts ...RequestOption) (*RawResponse[*Iterator[ListLicenseKeyInstancesResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, licenseKey, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Get retrieve a license instance
// Retrieve an activation using the license key ID and the instance UUID. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *LicensesInstanceService) Get(ctx context.Context, licenseKey int, instance string, opts ...RequestOption) (*SdkGetLicenseInstanceResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getLicenseInstance", false)}, opts...)
	var result SdkGetLicenseInstanceResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/license-keys/%s/instances/%s", url.PathEscape(fmt.Sprint(licenseKey)), url.PathEscape(fmt.Sprint(instance))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *LicensesInstanceService) GetWithResponse(ctx context.Context, licenseKey int, instance string, opts ...RequestOption) (*RawResponse[*SdkGetLicenseInstanceResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, licenseKey, instance, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
