// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
)

// LineItemService handles LineItems operations.
type LineItemService struct {
	client *Client
}

// LineItemsListParams contains the parameters for List.
type LineItemsListParams struct {
	// Limit is maximum number of line items per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is one-based result page.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
}

// List order line items
// List purchase line items for the selected store. Requires the `invoice` API-key ability or the corresponding OAuth scope and current store permission. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *LineItemService) List(ctx context.Context, params *LineItemsListParams, opts ...RequestOption) *Iterator[ListOrderLineItemsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("listOrderLineItems", false)}, opts...)
	return newIterator[ListOrderLineItemsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", "/v2/line-items", params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *LineItemService) ListWithResponse(ctx context.Context, params *LineItemsListParams, opts ...RequestOption) (*RawResponse[*Iterator[ListOrderLineItemsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// LineItemsSearchParams contains the parameters for Search.
type LineItemsSearchParams struct {
	Filters    []*SearchOrderLineItemsRequestApplicationJSONPropertyFiltersItem `json:"filters,omitempty" url:"-"`
	Sort       []*SearchOrderLineItemsRequestApplicationJSONPropertySortItem    `json:"sort,omitempty" url:"-"`
	Pagination *SearchOrderLineItemsRequestApplicationJSONPropertyPagination    `json:"pagination,omitempty" url:"-"`
}

// MarshalJSON implements json.Marshaler for LineItemsSearchParams.
func (p LineItemsSearchParams) MarshalJSON() ([]byte, error) {
	type Alias LineItemsSearchParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if p.Filters == nil && p.Sort == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Filters != nil {
		m["filters"] = p.Filters
	}
	if p.Sort != nil {
		m["sort"] = p.Sort
	}
	return json.Marshal(m)
}

// Search order line items
// Search product-level sale records with filters and sorting. Requires the `invoice` token ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *LineItemService) Search(ctx context.Context, params *LineItemsSearchParams, opts ...RequestOption) *Iterator[SearchOrderLineItemsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("searchOrderLineItems", false)}, opts...)
	return newIterator[SearchOrderLineItemsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "POST", "/v2/line-items/search", nil, "after", "data", opts, nil, paginationRequestBody{value: func() any {
		if params == nil {
			return nil
		}
		return schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkSearchOrderLineItemsRequestApplicationJson\",\"properties\":{\"filters\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItem\",\"properties\":{\"field\":{\"kind\":\"primitive\",\"type\":\"string\"},\"operator\":{\"kind\":\"enum\",\"values\":[\"eq\",\"in\",\"contains\",\"gt\",\"gte\",\"lt\",\"lte\"]},\"value\":{\"kind\":\"primitive\",\"type\":\"unknown\"}},\"required\":[\"field\",\"operator\",\"value\"],\"additionalProperties\":false},\"constraints\":{\"maxItems\":25}},\"sort\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchOrderLineItemsRequestApplicationJsonPropertySortItem\",\"properties\":{\"field\":{\"kind\":\"enum\",\"values\":[\"created_at\",\"total\",\"revenue\",\"quantity\"]},\"direction\":{\"kind\":\"enum\",\"values\":[\"asc\",\"desc\"]}},\"required\":[\"field\",\"direction\"],\"additionalProperties\":false},\"constraints\":{\"maxItems\":4}},\"pagination\":{\"kind\":\"object\",\"modelName\":\"SearchOrderLineItemsRequestApplicationJsonPropertyPagination\",\"properties\":{\"page\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}},\"limit\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1,\"maximum\":100}}},\"required\":[],\"additionalProperties\":false}},\"required\":[],\"additionalProperties\":false}"))
	}(), pageField: "pagination"})
}

func (s *LineItemService) SearchWithResponse(ctx context.Context, params *LineItemsSearchParams, opts ...RequestOption) (*RawResponse[*Iterator[SearchOrderLineItemsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.Search(ctx, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Get retrieve an order line item
// Retrieve one product-level sale record for the selected store. Requires the `invoice` token ability. Records from another store or whose order does not match the store return `404`. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *LineItemService) Get(ctx context.Context, lineItem int, opts ...RequestOption) (*SdkGetOrderLineItemResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getOrderLineItem", false)}, opts...)
	var result SdkGetOrderLineItemResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/line-items/%s", url.PathEscape(fmt.Sprint(lineItem))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *LineItemService) GetWithResponse(ctx context.Context, lineItem int, opts ...RequestOption) (*RawResponse[*SdkGetOrderLineItemResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, lineItem, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
