// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestOAuth_GetAuthorizationServerMetadata(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/.well-known/oauth-authorization-server", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_oauth_authorization_server_metadata_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithBrowserSession("sell_session=browser_test"))
	result, err := client.OAuth().GetAuthorizationServerMetadata(context.Background())
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "test_issuer", result.Issuer)
	require.Equal(t, "test_authorization_endpoint", result.AuthorizationEndpoint)
}

func TestOAuth_GetAuthorizationRequest(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/oauth/authorize", r.URL.Path)
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithBrowserSession("sell_session=browser_test"))
	err := client.OAuth().GetAuthorizationRequest(context.Background(), &sellapp.OAuthGetAuthorizationRequestParams{})
	require.NoError(t, err)
}

func TestOAuth_ApproveAuthorization(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/oauth/authorize", r.URL.Path)
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithBrowserSession("sell_session=browser_test"))
	err := client.OAuth().ApproveAuthorization(context.Background(), decodeTestParams[sellapp.OAuthApproveAuthorizationParams](t, "{\"auth_token\":\"test_auth_token\",\"client_id\":\"00000000-0000-0000-0000-000000000000\",\"state\":\"test_state\",\"_token\":\"test__token\"}"))
	require.NoError(t, err)
}

func TestOAuth_DenyAuthorization(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/oauth/authorize", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithBrowserSession("sell_session=browser_test"))
	err := client.OAuth().DenyAuthorization(context.Background(), decodeTestParams[sellapp.OAuthDenyAuthorizationParams](t, "{\"auth_token\":\"test_auth_token\",\"_token\":\"test__token\"}"))
	require.NoError(t, err)
}

func TestOAuth_ExchangeToken(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/oauth/token", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_exchange_oauth_token_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithBrowserSession("sell_session=browser_test"))
	result, err := client.OAuth().ExchangeToken(context.Background(), &sellapp.OAuthExchangeTokenParams{Body: decodeTestValue(t, "{\"client_id\":\"00000000-0000-0000-0000-000000000000\",\"client_secret\":\"test_client_secret\",\"grant_type\":\"authorization_code\",\"code\":\"test_code\",\"redirect_uri\":\"https://example.com\",\"code_verifier\":\"test_code_verifierxxxxxxxxxxxxxxxxxxxxxxxxx\"}")})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "test_access_token", result.AccessToken)
	require.Equal(t, "test_refresh_token", result.RefreshToken)
}

func TestOAuth_RevokeToken(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/oauth/revoke", r.URL.Path)
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithBrowserSession("sell_session=browser_test"))
	err := client.OAuth().RevokeToken(context.Background(), decodeTestParams[sellapp.OAuthRevokeTokenParams](t, "{\"client_id\":\"00000000-0000-0000-0000-000000000000\",\"client_secret\":\"test_client_secret\",\"token\":\"test_token\",\"token_type_hint\":\"access_token\"}"))
	require.NoError(t, err)
}

func TestOAuth_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithBrowserSession("sell_session=browser_test"))
	_, err := client.OAuth().GetAuthorizationServerMetadata(context.Background())
	require.IsType(t, &sellapp.AuthenticationError{}, err)
}

func TestOAuth_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithBrowserSession("sell_session=browser_test"))
	_, err := client.OAuth().GetAuthorizationServerMetadata(context.Background())
	require.IsType(t, &sellapp.NotFoundError{}, err)
}

func TestOAuth_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithBrowserSession("sell_session=browser_test"))
	_, err := client.OAuth().GetAuthorizationServerMetadata(context.Background())
	require.IsType(t, &sellapp.UnprocessableEntityError{}, err)
}
