// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile

func TestOAuthManagement_GetInstallation(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/oauth/installation", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_oauth_installation_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithAccessToken("oauth_test"))
	result, err := client.OAuthManagement().GetInstallation(context.Background())
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestOAuthManagement_DeleteInstallation(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v2/oauth/installation", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithAccessToken("oauth_test"))
	err := client.OAuthManagement().DeleteInstallation(context.Background())
	require.NoError(t, err)
}

func TestOAuthManagement_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithAccessToken("oauth_test"))
	_, err := client.OAuthManagement().GetInstallation(context.Background())
	require.IsType(t, &sellapp.AuthenticationError{}, err)
}

func TestOAuthManagement_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithAccessToken("oauth_test"))
	_, err := client.OAuthManagement().GetInstallation(context.Background())
	require.IsType(t, &sellapp.NotFoundError{}, err)
}

func TestOAuthManagement_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL), sellapp.WithAccessToken("oauth_test"))
	_, err := client.OAuthManagement().GetInstallation(context.Background())
	require.IsType(t, &sellapp.UnprocessableEntityError{}, err)
}
