// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
)

// OrdersLineItemService handles OrdersLineItems operations.
type OrdersLineItemService struct {
	client *Client
}

// OrdersLineItemsListParams contains the parameters for List.
type OrdersLineItemsListParams struct {
	// Limit is maximum number of line items per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is one-based result page.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
}

// List an order's line items
// List purchase line items for the selected store. Requires the `invoice` API-key ability or the corresponding OAuth scope and current store permission. The order path parameter scopes the result and must match the line item's parent order. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *OrdersLineItemService) List(ctx context.Context, order int, params *OrdersLineItemsListParams, opts ...RequestOption) *Iterator[ListOrderSLineItemsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("listOrderSLineItems", false)}, opts...)
	return newIterator[ListOrderSLineItemsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", fmt.Sprintf("/v2/orders/%s/line-items", url.PathEscape(fmt.Sprint(order))), params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *OrdersLineItemService) ListWithResponse(ctx context.Context, order int, params *OrdersLineItemsListParams, opts ...RequestOption) (*RawResponse[*Iterator[ListOrderSLineItemsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, order, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// OrdersLineItemsSearchParams contains the parameters for Search.
type OrdersLineItemsSearchParams struct {
	Filters    []*SearchOrderSLineItemsRequestApplicationJSONPropertyFiltersItem `json:"filters,omitempty" url:"-"`
	Sort       []*SearchOrderSLineItemsRequestApplicationJSONPropertySortItem    `json:"sort,omitempty" url:"-"`
	Pagination *SearchOrderSLineItemsRequestApplicationJSONPropertyPagination    `json:"pagination,omitempty" url:"-"`
}

// MarshalJSON implements json.Marshaler for OrdersLineItemsSearchParams.
func (p OrdersLineItemsSearchParams) MarshalJSON() ([]byte, error) {
	type Alias OrdersLineItemsSearchParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if p.Filters == nil && p.Sort == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Filters != nil {
		m["filters"] = p.Filters
	}
	if p.Sort != nil {
		m["sort"] = p.Sort
	}
	return json.Marshal(m)
}

// Search an order's line items
// Search product-level sale records with filters and sorting. Requires the `invoice` token ability. The order path parameter scopes the result and must match the line item's parent order. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *OrdersLineItemService) Search(ctx context.Context, order int, params *OrdersLineItemsSearchParams, opts ...RequestOption) *Iterator[SearchOrderSLineItemsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("searchOrderSLineItems", false)}, opts...)
	return newIterator[SearchOrderSLineItemsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "POST", fmt.Sprintf("/v2/orders/%s/line-items/search", url.PathEscape(fmt.Sprint(order))), nil, "after", "data", opts, nil, paginationRequestBody{value: func() any {
		if params == nil {
			return nil
		}
		return schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkSearchOrderSLineItemsRequestApplicationJson\",\"properties\":{\"filters\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchOrderSLineItemsRequestApplicationJsonPropertyFiltersItem\",\"properties\":{\"field\":{\"kind\":\"primitive\",\"type\":\"string\"},\"operator\":{\"kind\":\"enum\",\"values\":[\"eq\",\"in\",\"contains\",\"gt\",\"gte\",\"lt\",\"lte\"]},\"value\":{\"kind\":\"primitive\",\"type\":\"unknown\"}},\"required\":[\"field\",\"operator\",\"value\"],\"additionalProperties\":false},\"constraints\":{\"maxItems\":25}},\"sort\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchOrderSLineItemsRequestApplicationJsonPropertySortItem\",\"properties\":{\"field\":{\"kind\":\"enum\",\"values\":[\"created_at\",\"total\",\"revenue\",\"quantity\"]},\"direction\":{\"kind\":\"enum\",\"values\":[\"asc\",\"desc\"]}},\"required\":[\"field\",\"direction\"],\"additionalProperties\":false},\"constraints\":{\"maxItems\":4}},\"pagination\":{\"kind\":\"object\",\"modelName\":\"SearchOrderSLineItemsRequestApplicationJsonPropertyPagination\",\"properties\":{\"page\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}},\"limit\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1,\"maximum\":100}}},\"required\":[],\"additionalProperties\":false}},\"required\":[],\"additionalProperties\":false}"))
	}(), pageField: "pagination"})
}

func (s *OrdersLineItemService) SearchWithResponse(ctx context.Context, order int, params *OrdersLineItemsSearchParams, opts ...RequestOption) (*RawResponse[*Iterator[SearchOrderSLineItemsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.Search(ctx, order, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Get retrieve an order's line item
// Retrieve one product-level sale record for the selected store. Requires the `invoice` token ability. Records from another store or whose order does not match the store return `404`. The order path parameter scopes the result and must match the line item's parent order. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *OrdersLineItemService) Get(ctx context.Context, order int, lineItem int, opts ...RequestOption) (*SdkGetOrderSLineItemResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getOrderSLineItem", false)}, opts...)
	var result SdkGetOrderSLineItemResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/orders/%s/line-items/%s", url.PathEscape(fmt.Sprint(order)), url.PathEscape(fmt.Sprint(lineItem))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *OrdersLineItemService) GetWithResponse(ctx context.Context, order int, lineItem int, opts ...RequestOption) (*RawResponse[*SdkGetOrderSLineItemResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, order, lineItem, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
