// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestProductVariantsBooking_ListAvailability(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/products/1/variants/1/booking/availability", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_list_booking_availability_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.ProductVariantsBooking().ListAvailability(context.Background(), 1, 1, &sellapp.ProductVariantsBookingListAvailabilityParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestProductVariantsBooking_CreateHold(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/products/1/variants/1/booking/holds", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_create_booking_hold_response_value_201_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.ProductVariantsBooking().CreateHold(context.Background(), 1, 1, decodeTestParams[sellapp.ProductVariantsBookingCreateHoldParams](t, "{\"slot_start_at\":\"2023-01-01T00:00:00.000Z\",\"quantity\":1,\"customer_key\":\"test_customer_key\",\"meta\":{}}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestProductVariantsBooking_ReleaseHold(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v2/products/1/variants/booking/holds/test_hold", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.ProductVariantsBooking().ReleaseHold(context.Background(), 1, "test_hold", decodeTestParams[sellapp.ProductVariantsBookingReleaseHoldParams](t, "{\"customer_key\":\"test_customer_key\"}"))
	require.NoError(t, err)
}

func TestProductVariantsBooking_Get(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/products/test_product/variants/1/booking", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_booking_configuration_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.ProductVariantsBooking().Get(context.Background(), "test_product", 1)
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestProductVariantsBooking_Replace(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/products/test_product/variants/1/booking", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_booking_configuration_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.ProductVariantsBooking().Replace(context.Background(), "test_product", 1, decodeTestParams[sellapp.ProductVariantsBookingReplaceParams](t, "{\"mode\":\"native\",\"conflict_scope\":\"product\",\"timezone\":\"America/New_York\",\"duration_minutes\":30,\"capacity_per_slot\":1,\"min_notice_minutes\":1,\"max_advance_days\":1,\"buffer_before_minutes\":30,\"buffer_after_minutes\":30,\"availability\":[{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"}],\"provider_connection_ids\":[1],\"video_provider\":\"none\",\"video_provider_connection_id\":1,\"reminders_enabled\":true,\"reminder_offset_value\":1,\"reminder_offset_unit\":\"minutes\",\"meta\":{}}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestProductVariantsBooking_Update(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/products/test_product/variants/1/booking", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_booking_configuration_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.ProductVariantsBooking().Update(context.Background(), "test_product", 1, decodeTestParams[sellapp.ProductVariantsBookingUpdateParams](t, "{\"mode\":\"native\",\"conflict_scope\":\"product\",\"timezone\":\"America/New_York\",\"duration_minutes\":30,\"capacity_per_slot\":1,\"min_notice_minutes\":1,\"max_advance_days\":1,\"buffer_before_minutes\":30,\"buffer_after_minutes\":30,\"availability\":[{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"},{\"day\":1,\"enabled\":true,\"start\":\"09:00\",\"end\":\"17:00\"}],\"provider_connection_ids\":[1],\"video_provider\":\"none\",\"video_provider_connection_id\":1,\"reminders_enabled\":true,\"reminder_offset_value\":1,\"reminder_offset_unit\":\"minutes\",\"meta\":{}}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestProductVariantsBooking_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.ProductVariantsBooking().ListAvailability(context.Background(), 1, 1, &sellapp.ProductVariantsBookingListAvailabilityParams{})
	require.IsType(t, &sellapp.AuthenticationError{}, err)
}

func TestProductVariantsBooking_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.ProductVariantsBooking().ListAvailability(context.Background(), 1, 1, &sellapp.ProductVariantsBookingListAvailabilityParams{})
	require.IsType(t, &sellapp.NotFoundError{}, err)
}

func TestProductVariantsBooking_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.ProductVariantsBooking().ListAvailability(context.Background(), 1, 1, &sellapp.ProductVariantsBookingListAvailabilityParams{})
	require.IsType(t, &sellapp.UnprocessableEntityError{}, err)
}
