// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"fmt"
	"net/url"
)

// ProductsAddonService handles ProductsAddons operations.
type ProductsAddonService struct {
	client *Client
}

// ProductsAddonsListParams contains the parameters for List.
type ProductsAddonsListParams struct {
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
	// Pagination is set to false to return at most 100 matching items in one data array without pagination links or metadata.
	// Defaults to true.
	Pagination *bool `url:"pagination,omitempty" json:"-"`
}

// List a product's add-ons
// Retrieve the ordered add-ons assigned to a product, course, or booking. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *ProductsAddonService) List(ctx context.Context, product int, params *ProductsAddonsListParams, opts ...RequestOption) *Iterator[SdkListProductSAddOnsResponseValue200ApplicationJSON] {
	opts = append([]RequestOption{withOperation("listProductSAddOns", false)}, opts...)
	return newIterator[SdkListProductSAddOnsResponseValue200ApplicationJSON](ctx, s.client, "GET", fmt.Sprintf("/v2/products/%s/addons", url.PathEscape(fmt.Sprint(product))), params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *ProductsAddonService) ListWithResponse(ctx context.Context, product int, params *ProductsAddonsListParams, opts ...RequestOption) (*RawResponse[*Iterator[SdkListProductSAddOnsResponseValue200ApplicationJSON]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, product, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// ProductsAddonsReplaceParams contains the parameters for Replace.
type ProductsAddonsReplaceParams struct {
	Resources []int `json:"resources" url:"-"`
}

// Replace a product's add-ons
// Replace the complete ordered add-on assignment for a non-subscription product, course, or booking. Newly assigned add-ons must be published, public, and owned by the same store; already assigned non-public add-ons may be retained for safe editing. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *ProductsAddonService) Replace(ctx context.Context, product int, params *ProductsAddonsReplaceParams, opts ...RequestOption) (*SdkReplaceProductSAddOnsResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("replaceProductSAddOns", false)}, opts...)
	var result SdkReplaceProductSAddOnsResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/v2/products/%s/addons", url.PathEscape(fmt.Sprint(product))), nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkReplaceProductSAddOnsRequestApplicationJson\",\"properties\":{\"resources\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"constraints\":{\"uniqueItems\":true}}},\"required\":[\"resources\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *ProductsAddonService) ReplaceWithResponse(ctx context.Context, product int, params *ProductsAddonsReplaceParams, opts ...RequestOption) (*RawResponse[*SdkReplaceProductSAddOnsResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Replace(ctx, product, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
