// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestPromotionsPhases_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/promotions/1/phases", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_list_promotion_phases_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.PromotionsPhases().List(context.Background(), 1)
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestPromotionsPhases_Replace(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/promotions/1/phases", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_replace_promotion_phases_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.PromotionsPhases().Replace(context.Background(), 1, decodeTestParams[sellapp.PromotionsPhasesReplaceParams](t, "{\"phases\":[{\"discount_type\":\"percentage\",\"discount_value\":1,\"ends_at\":\"2023-01-01T00:00:00.000Z\",\"max_redemptions\":1,\"minimum_amount\":1}]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestPromotionsPhases_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.PromotionsPhases().List(context.Background(), 1)
	require.IsType(t, &sellapp.AuthenticationError{}, err)
}

func TestPromotionsPhases_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.PromotionsPhases().List(context.Background(), 1)
	require.IsType(t, &sellapp.NotFoundError{}, err)
}

func TestPromotionsPhases_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.PromotionsPhases().List(context.Background(), 1)
	require.IsType(t, &sellapp.UnprocessableEntityError{}, err)
}
