// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestSections_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v1/sections", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"title\":\"test_title\",\"slug\":\"test_slug\",\"hidden\":true,\"order\":1,\"created_at\":\"2023-01-01T00:00:00.000Z\",\"updated_at\":\"2023-01-01T00:00:00.000Z\",\"store_id\":1,\"groups_linked\":1,\"products_linked\":1,\"groups\":[{\"id\":1,\"title\":\"test_title\",\"group_products\":1}],\"products\":[{\"id\":\"01234\",\"title\":\"test_title\",\"description\":\"test_description\"}]}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().List(context.Background(), &sellapp.SectionsListParams{Limit: ptrInt(10)})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestSections_List_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().List(context.Background(), &sellapp.SectionsListParams{Limit: ptrInt(10)})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestSections_Create(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v1/sections", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().Create(context.Background(), decodeTestParams[sellapp.SectionsCreateParams](t, "{\"title\":\"test_title\",\"hidden\":true}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_Get(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v1/sections/1", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().Get(context.Background(), 1)
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_Replace(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v1/sections/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().Replace(context.Background(), 1, decodeTestParams[sellapp.SectionsReplaceParams](t, "{\"title\":\"test_title\",\"hidden\":true}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_Update(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v1/sections/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().Update(context.Background(), 1, decodeTestParams[sellapp.SectionsUpdateParams](t, "{\"title\":\"test_title\",\"hidden\":true}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_Delete(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v1/sections/1", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.Sections().Delete(context.Background(), 1)
	require.NoError(t, err)
}

func TestSections_ReplaceOrder(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v1/sections/order", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_replace_section_order_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().ReplaceOrder(context.Background(), decodeTestParams[sellapp.SectionsReplaceOrderParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_ReplaceProducts(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v1/sections/1/products", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().ReplaceProducts(context.Background(), 1, decodeTestParams[sellapp.SectionsReplaceProductsParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_ReplaceGroups(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v1/sections/1/groups", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().ReplaceGroups(context.Background(), 1, decodeTestParams[sellapp.SectionsReplaceGroupsParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_Search(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v1/sections/search", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"title\":\"test_title\",\"slug\":\"test_slug\",\"hidden\":true,\"order\":1,\"created_at\":\"2023-01-01T00:00:00.000Z\",\"updated_at\":\"2023-01-01T00:00:00.000Z\",\"store_id\":1,\"groups_linked\":1,\"products_linked\":1,\"groups\":[{\"id\":1,\"title\":\"test_title\",\"group_products\":1}],\"products\":[{\"id\":\"01234\",\"title\":\"test_title\",\"description\":\"test_description\"}]}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().Search(context.Background(), &sellapp.SectionsSearchParams{})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestSections_Search_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().Search(context.Background(), &sellapp.SectionsSearchParams{})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestSections_BatchCreate(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v1/sections/batch", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_replace_section_order_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().BatchCreate(context.Background(), decodeTestParams[sellapp.SectionsBatchCreateParams](t, "{\"resources\":[{\"title\":\"test_title\",\"hidden\":true}]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_BatchUpdate(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v1/sections/batch", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_replace_section_order_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().BatchUpdate(context.Background(), decodeTestParams[sellapp.SectionsBatchUpdateParams](t, "{\"resources\":{}}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_BatchDelete(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v1/sections/batch", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.Sections().BatchDelete(context.Background(), decodeTestParams[sellapp.SectionsBatchDeleteParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
}

func TestSections_V2ListSections(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/sections", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"title\":\"test_title\",\"slug\":\"test_slug\",\"hidden\":true,\"order\":1,\"created_at\":\"2023-01-01T00:00:00.000Z\",\"updated_at\":\"2023-01-01T00:00:00.000Z\",\"store_id\":1,\"groups_linked\":1,\"products_linked\":1,\"groups\":[{\"id\":1,\"title\":\"test_title\",\"group_products\":1}],\"products\":[{\"id\":\"01234\",\"title\":\"test_title\",\"description\":\"test_description\"}]}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().V2ListSections(context.Background(), &sellapp.SectionsV2ListSectionsParams{Limit: ptrInt(10)})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestSections_V2ListSections_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().V2ListSections(context.Background(), &sellapp.SectionsV2ListSectionsParams{Limit: ptrInt(10)})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestSections_V2CreateSection(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/sections", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().V2CreateSection(context.Background(), decodeTestParams[sellapp.SectionsV2CreateSectionParams](t, "{\"title\":\"test_title\",\"hidden\":true}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_V2SearchSections(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/sections/search", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("{\"data\":[{\"id\":1,\"title\":\"test_title\",\"slug\":\"test_slug\",\"hidden\":true,\"order\":1,\"created_at\":\"2023-01-01T00:00:00.000Z\",\"updated_at\":\"2023-01-01T00:00:00.000Z\",\"store_id\":1,\"groups_linked\":1,\"products_linked\":1,\"groups\":[{\"id\":1,\"title\":\"test_title\",\"group_products\":1}],\"products\":[{\"id\":\"01234\",\"title\":\"test_title\",\"description\":\"test_description\"}]}],\"links\":{\"next\":null},\"list_metadata\":{\"before\":null,\"after\":null}}"))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().V2SearchSections(context.Background(), &sellapp.SectionsV2SearchSectionsParams{})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestSections_V2SearchSections_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().V2SearchSections(context.Background(), &sellapp.SectionsV2SearchSectionsParams{})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestSections_V2GetSection(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/sections/1", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().V2GetSection(context.Background(), 1)
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_V2ReplaceSection(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/sections/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().V2ReplaceSection(context.Background(), 1, decodeTestParams[sellapp.SectionsV2ReplaceSectionParams](t, "{\"title\":\"test_title\",\"hidden\":true}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_V2UpdateSection(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/sections/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().V2UpdateSection(context.Background(), 1, decodeTestParams[sellapp.SectionsV2UpdateSectionParams](t, "{\"title\":\"test_title\",\"hidden\":true}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_V2DeleteSection(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v2/sections/1", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.Sections().V2DeleteSection(context.Background(), 1)
	require.NoError(t, err)
}

func TestSections_V2BatchCreateSections(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/sections/batch", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_replace_section_order_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().V2BatchCreateSections(context.Background(), decodeTestParams[sellapp.SectionsV2BatchCreateSectionsParams](t, "{\"resources\":[{\"title\":\"test_title\",\"hidden\":true}]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_V2BatchUpdateSections(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/sections/batch", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_replace_section_order_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().V2BatchUpdateSections(context.Background(), decodeTestParams[sellapp.SectionsV2BatchUpdateSectionsParams](t, "{\"resources\":{}}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_V2BatchDeleteSections(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v2/sections/batch", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.Sections().V2BatchDeleteSections(context.Background(), decodeTestParams[sellapp.SectionsV2BatchDeleteSectionsParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
}

func TestSections_V2ReplaceSectionOrder(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/sections/order", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_replace_section_order_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().V2ReplaceSectionOrder(context.Background(), decodeTestParams[sellapp.SectionsV2ReplaceSectionOrderParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_V2ReplaceSectionProducts(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/sections/1/products", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().V2ReplaceSectionProducts(context.Background(), 1, decodeTestParams[sellapp.SectionsV2ReplaceSectionProductsParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_V2ReplaceSectionGroups(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/sections/1/groups", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_section_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.Sections().V2ReplaceSectionGroups(context.Background(), 1, decodeTestParams[sellapp.SectionsV2ReplaceSectionGroupsParams](t, "{\"resources\":[1]}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestSections_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().List(context.Background(), &sellapp.SectionsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.AuthenticationError{}, iter.Err())
}

func TestSections_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().List(context.Background(), &sellapp.SectionsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.NotFoundError{}, iter.Err())
}

func TestSections_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	iter := client.Sections().List(context.Background(), &sellapp.SectionsListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &sellapp.UnprocessableEntityError{}, iter.Err())
}
