// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"net/http"
	"os"
)

// Client is the SellApp API client.
type Client struct {
	apiKey                                                               string
	accessToken, customerSession, browserSession, clientID, clientSecret string
	store                                                                string
	baseURL                                                              string
	httpClient                                                           *http.Client
	maxRetries                                                           int
	logger                                                               Logger
	appInfo                                                              appInfo
	configErr                                                            error
	hook                                                                 RequestHook

	charges                     *ChargeService
	groups                      *GroupService
	groupsProducts              *GroupsProductService
	invoices                    *InvoiceService
	licenses                    *LicenseService
	licensesInstances           *LicensesInstanceService
	licenseInstances            *LicenseInstanceService
	products                    *ProductService
	productVariants             *ProductVariantService
	productVariantsPricing      *ProductVariantsPricingService
	productVariantsBooking      *ProductVariantsBookingService
	subscriptions               *SubscriptionService
	bookings                    *BookingService
	bookingsCalendarEvents      *BookingsCalendarEventService
	bundleItems                 *BundleItemService
	promotions                  *PromotionService
	promotionsPhases            *PromotionsPhaseService
	addOns                      *AddOnService
	addOnsParentProducts        *AddOnsParentProductService
	productsAddons              *ProductsAddonService
	highlights                  *HighlightService
	highlightsMedia             *HighlightsMediaService
	webhookChannels             *WebhookChannelService
	customers                   *CustomerService
	orders                      *OrderService
	lineItems                   *LineItemService
	ordersLineItems             *OrdersLineItemService
	variantDeliverables         *VariantDeliverableService
	variantDeliverableFiles     *VariantDeliverableFileService
	variantDeliverableFolders   *VariantDeliverableFolderService
	variantSerials              *VariantSerialService
	affiliateProgram            *AffiliateProgramService
	rewardRules                 *RewardRuleService
	rewardCouponTemplates       *RewardCouponTemplateService
	rewardGrants                *RewardGrantService
	upsellOffers                *UpsellOfferService
	communityConnections        *CommunityConnectionService
	walletSettings              *WalletSettingService
	wallet                      *WalletService
	walletTransactions          *WalletTransactionService
	walletTopups                *WalletTopupService
	cashbackRules               *CashbackRuleService
	walletBonusTiers            *WalletBonusTierService
	courses                     *CourseService
	coursesSections             *CoursesSectionService
	coursesLessons              *CoursesLessonService
	paymentMethods              *PaymentMethodService
	paymentMethodsCustom        *PaymentMethodsCustomService
	storeSettings               *StoreSettingService
	storeNotificationChannels   *StoreNotificationChannelService
	storeCustomDomains          *StoreCustomDomainService
	creditsProducts             *CreditsProductService
	creditsBalances             *CreditsBalanceService
	credits                     *CreditService
	creditsBalancesTransactions *CreditsBalancesTransactionService
	affiliates                  *AffiliateService
	affiliateReferrals          *AffiliateReferralService
	affiliateReferralSessions   *AffiliateReferralSessionService
	affiliatePayouts            *AffiliatePayoutService
	refunds                     *RefundService
	exports                     *ExportService
	disputes                    *DisputeService
	entitlements                *EntitlementService
	customerSessions            *CustomerSessionService
	customerPortal              *CustomerPortalService
	events                      *EventService
	webhookPlatform             *WebhookPlatformService
	account                     *AccountService
	oAuthManagement             *OAuthManagementService
	blacklists                  *BlacklistService
	coupons                     *CouponService
	feedback                    *FeedbackService
	sections                    *SectionService
	tickets                     *TicketService
	ticketsMessages             *TicketsMessageService
	oAuth                       *OAuthService
}

// NewClient creates a new SellApp API client.
func NewClient(apiKey, store string, opts ...ClientOption) *Client {
	if apiKey == "" {
		apiKey = os.Getenv("SELLAPP_API_KEY")
	}
	if store == "" {
		store = os.Getenv("SELLAPP_STORE")
	}
	c := &Client{
		apiKey:     apiKey,
		store:      store,
		baseURL:    defaultBaseURL,
		httpClient: &http.Client{Timeout: defaultTimeout},
		maxRetries: defaultMaxRetries,
	}
	for _, opt := range opts {
		opt(c)
	}
	c.charges = &ChargeService{client: c}
	c.groups = &GroupService{client: c}
	c.groupsProducts = &GroupsProductService{client: c}
	c.invoices = &InvoiceService{client: c}
	c.licenses = &LicenseService{client: c}
	c.licensesInstances = &LicensesInstanceService{client: c}
	c.licenseInstances = &LicenseInstanceService{client: c}
	c.products = &ProductService{client: c}
	c.productVariants = &ProductVariantService{client: c}
	c.productVariantsPricing = &ProductVariantsPricingService{client: c}
	c.productVariantsBooking = &ProductVariantsBookingService{client: c}
	c.subscriptions = &SubscriptionService{client: c}
	c.bookings = &BookingService{client: c}
	c.bookingsCalendarEvents = &BookingsCalendarEventService{client: c}
	c.bundleItems = &BundleItemService{client: c}
	c.promotions = &PromotionService{client: c}
	c.promotionsPhases = &PromotionsPhaseService{client: c}
	c.addOns = &AddOnService{client: c}
	c.addOnsParentProducts = &AddOnsParentProductService{client: c}
	c.productsAddons = &ProductsAddonService{client: c}
	c.highlights = &HighlightService{client: c}
	c.highlightsMedia = &HighlightsMediaService{client: c}
	c.webhookChannels = &WebhookChannelService{client: c}
	c.customers = &CustomerService{client: c}
	c.orders = &OrderService{client: c}
	c.lineItems = &LineItemService{client: c}
	c.ordersLineItems = &OrdersLineItemService{client: c}
	c.variantDeliverables = &VariantDeliverableService{client: c}
	c.variantDeliverableFiles = &VariantDeliverableFileService{client: c}
	c.variantDeliverableFolders = &VariantDeliverableFolderService{client: c}
	c.variantSerials = &VariantSerialService{client: c}
	c.affiliateProgram = &AffiliateProgramService{client: c}
	c.rewardRules = &RewardRuleService{client: c}
	c.rewardCouponTemplates = &RewardCouponTemplateService{client: c}
	c.rewardGrants = &RewardGrantService{client: c}
	c.upsellOffers = &UpsellOfferService{client: c}
	c.communityConnections = &CommunityConnectionService{client: c}
	c.walletSettings = &WalletSettingService{client: c}
	c.wallet = &WalletService{client: c}
	c.walletTransactions = &WalletTransactionService{client: c}
	c.walletTopups = &WalletTopupService{client: c}
	c.cashbackRules = &CashbackRuleService{client: c}
	c.walletBonusTiers = &WalletBonusTierService{client: c}
	c.courses = &CourseService{client: c}
	c.coursesSections = &CoursesSectionService{client: c}
	c.coursesLessons = &CoursesLessonService{client: c}
	c.paymentMethods = &PaymentMethodService{client: c}
	c.paymentMethodsCustom = &PaymentMethodsCustomService{client: c}
	c.storeSettings = &StoreSettingService{client: c}
	c.storeNotificationChannels = &StoreNotificationChannelService{client: c}
	c.storeCustomDomains = &StoreCustomDomainService{client: c}
	c.creditsProducts = &CreditsProductService{client: c}
	c.creditsBalances = &CreditsBalanceService{client: c}
	c.credits = &CreditService{client: c}
	c.creditsBalancesTransactions = &CreditsBalancesTransactionService{client: c}
	c.affiliates = &AffiliateService{client: c}
	c.affiliateReferrals = &AffiliateReferralService{client: c}
	c.affiliateReferralSessions = &AffiliateReferralSessionService{client: c}
	c.affiliatePayouts = &AffiliatePayoutService{client: c}
	c.refunds = &RefundService{client: c}
	c.exports = &ExportService{client: c}
	c.disputes = &DisputeService{client: c}
	c.entitlements = &EntitlementService{client: c}
	c.customerSessions = &CustomerSessionService{client: c}
	c.customerPortal = &CustomerPortalService{client: c}
	c.events = &EventService{client: c}
	c.webhookPlatform = &WebhookPlatformService{client: c}
	c.account = &AccountService{client: c}
	c.oAuthManagement = &OAuthManagementService{client: c}
	c.blacklists = &BlacklistService{client: c}
	c.coupons = &CouponService{client: c}
	c.feedback = &FeedbackService{client: c}
	c.sections = &SectionService{client: c}
	c.tickets = &TicketService{client: c}
	c.ticketsMessages = &TicketsMessageService{client: c}
	c.oAuth = &OAuthService{client: c}
	return c
}

// Charges returns the Charges service.
func (c *Client) Charges() *ChargeService {
	return c.charges
}

// Groups returns the Groups service.
func (c *Client) Groups() *GroupService {
	return c.groups
}

// GroupsProducts returns the GroupsProducts service.
func (c *Client) GroupsProducts() *GroupsProductService {
	return c.groupsProducts
}

// Invoices returns the Invoices service.
func (c *Client) Invoices() *InvoiceService {
	return c.invoices
}

// Licenses returns the Licenses service.
func (c *Client) Licenses() *LicenseService {
	return c.licenses
}

// LicensesInstances returns the LicensesInstances service.
func (c *Client) LicensesInstances() *LicensesInstanceService {
	return c.licensesInstances
}

// LicenseInstances returns the LicenseInstances service.
func (c *Client) LicenseInstances() *LicenseInstanceService {
	return c.licenseInstances
}

// Products returns the Products service.
func (c *Client) Products() *ProductService {
	return c.products
}

// ProductVariants returns the ProductVariants service.
func (c *Client) ProductVariants() *ProductVariantService {
	return c.productVariants
}

// ProductVariantsPricing returns the ProductVariantsPricing service.
func (c *Client) ProductVariantsPricing() *ProductVariantsPricingService {
	return c.productVariantsPricing
}

// ProductVariantsBooking returns the ProductVariantsBooking service.
func (c *Client) ProductVariantsBooking() *ProductVariantsBookingService {
	return c.productVariantsBooking
}

// Subscriptions returns the Subscriptions service.
func (c *Client) Subscriptions() *SubscriptionService {
	return c.subscriptions
}

// Bookings returns the Bookings service.
func (c *Client) Bookings() *BookingService {
	return c.bookings
}

// BookingsCalendarEvents returns the BookingsCalendarEvents service.
func (c *Client) BookingsCalendarEvents() *BookingsCalendarEventService {
	return c.bookingsCalendarEvents
}

// BundleItems returns the BundleItems service.
func (c *Client) BundleItems() *BundleItemService {
	return c.bundleItems
}

// Promotions returns the Promotions service.
func (c *Client) Promotions() *PromotionService {
	return c.promotions
}

// PromotionsPhases returns the PromotionsPhases service.
func (c *Client) PromotionsPhases() *PromotionsPhaseService {
	return c.promotionsPhases
}

// AddOns returns the AddOns service.
func (c *Client) AddOns() *AddOnService {
	return c.addOns
}

// AddOnsParentProducts returns the AddOnsParentProducts service.
func (c *Client) AddOnsParentProducts() *AddOnsParentProductService {
	return c.addOnsParentProducts
}

// ProductsAddons returns the ProductsAddons service.
func (c *Client) ProductsAddons() *ProductsAddonService {
	return c.productsAddons
}

// Highlights returns the Highlights service.
func (c *Client) Highlights() *HighlightService {
	return c.highlights
}

// HighlightsMedia returns the HighlightsMedia service.
func (c *Client) HighlightsMedia() *HighlightsMediaService {
	return c.highlightsMedia
}

// WebhookChannels returns the WebhookChannels service.
func (c *Client) WebhookChannels() *WebhookChannelService {
	return c.webhookChannels
}

// Customers returns the Customers service.
func (c *Client) Customers() *CustomerService {
	return c.customers
}

// Orders returns the Orders service.
func (c *Client) Orders() *OrderService {
	return c.orders
}

// LineItems returns the LineItems service.
func (c *Client) LineItems() *LineItemService {
	return c.lineItems
}

// OrdersLineItems returns the OrdersLineItems service.
func (c *Client) OrdersLineItems() *OrdersLineItemService {
	return c.ordersLineItems
}

// VariantDeliverables returns the VariantDeliverables service.
func (c *Client) VariantDeliverables() *VariantDeliverableService {
	return c.variantDeliverables
}

// VariantDeliverableFiles returns the VariantDeliverableFiles service.
func (c *Client) VariantDeliverableFiles() *VariantDeliverableFileService {
	return c.variantDeliverableFiles
}

// VariantDeliverableFolders returns the VariantDeliverableFolders service.
func (c *Client) VariantDeliverableFolders() *VariantDeliverableFolderService {
	return c.variantDeliverableFolders
}

// VariantSerials returns the VariantSerials service.
func (c *Client) VariantSerials() *VariantSerialService {
	return c.variantSerials
}

// AffiliateProgram returns the AffiliateProgram service.
func (c *Client) AffiliateProgram() *AffiliateProgramService {
	return c.affiliateProgram
}

// RewardRules returns the RewardRules service.
func (c *Client) RewardRules() *RewardRuleService {
	return c.rewardRules
}

// RewardCouponTemplates returns the RewardCouponTemplates service.
func (c *Client) RewardCouponTemplates() *RewardCouponTemplateService {
	return c.rewardCouponTemplates
}

// RewardGrants returns the RewardGrants service.
func (c *Client) RewardGrants() *RewardGrantService {
	return c.rewardGrants
}

// UpsellOffers returns the UpsellOffers service.
func (c *Client) UpsellOffers() *UpsellOfferService {
	return c.upsellOffers
}

// CommunityConnections returns the CommunityConnections service.
func (c *Client) CommunityConnections() *CommunityConnectionService {
	return c.communityConnections
}

// WalletSettings returns the WalletSettings service.
func (c *Client) WalletSettings() *WalletSettingService {
	return c.walletSettings
}

// Wallet returns the Wallet service.
func (c *Client) Wallet() *WalletService {
	return c.wallet
}

// WalletTransactions returns the WalletTransactions service.
func (c *Client) WalletTransactions() *WalletTransactionService {
	return c.walletTransactions
}

// WalletTopups returns the WalletTopups service.
func (c *Client) WalletTopups() *WalletTopupService {
	return c.walletTopups
}

// CashbackRules returns the CashbackRules service.
func (c *Client) CashbackRules() *CashbackRuleService {
	return c.cashbackRules
}

// WalletBonusTiers returns the WalletBonusTiers service.
func (c *Client) WalletBonusTiers() *WalletBonusTierService {
	return c.walletBonusTiers
}

// Courses returns the Courses service.
func (c *Client) Courses() *CourseService {
	return c.courses
}

// CoursesSections returns the CoursesSections service.
func (c *Client) CoursesSections() *CoursesSectionService {
	return c.coursesSections
}

// CoursesLessons returns the CoursesLessons service.
func (c *Client) CoursesLessons() *CoursesLessonService {
	return c.coursesLessons
}

// PaymentMethods returns the PaymentMethods service.
func (c *Client) PaymentMethods() *PaymentMethodService {
	return c.paymentMethods
}

// PaymentMethodsCustom returns the PaymentMethodsCustom service.
func (c *Client) PaymentMethodsCustom() *PaymentMethodsCustomService {
	return c.paymentMethodsCustom
}

// StoreSettings returns the StoreSettings service.
func (c *Client) StoreSettings() *StoreSettingService {
	return c.storeSettings
}

// StoreNotificationChannels returns the StoreNotificationChannels service.
func (c *Client) StoreNotificationChannels() *StoreNotificationChannelService {
	return c.storeNotificationChannels
}

// StoreCustomDomains returns the StoreCustomDomains service.
func (c *Client) StoreCustomDomains() *StoreCustomDomainService {
	return c.storeCustomDomains
}

// CreditsProducts returns the CreditsProducts service.
func (c *Client) CreditsProducts() *CreditsProductService {
	return c.creditsProducts
}

// CreditsBalances returns the CreditsBalances service.
func (c *Client) CreditsBalances() *CreditsBalanceService {
	return c.creditsBalances
}

// Credits returns the Credits service.
func (c *Client) Credits() *CreditService {
	return c.credits
}

// CreditsBalancesTransactions returns the CreditsBalancesTransactions service.
func (c *Client) CreditsBalancesTransactions() *CreditsBalancesTransactionService {
	return c.creditsBalancesTransactions
}

// Affiliates returns the Affiliates service.
func (c *Client) Affiliates() *AffiliateService {
	return c.affiliates
}

// AffiliateReferrals returns the AffiliateReferrals service.
func (c *Client) AffiliateReferrals() *AffiliateReferralService {
	return c.affiliateReferrals
}

// AffiliateReferralSessions returns the AffiliateReferralSessions service.
func (c *Client) AffiliateReferralSessions() *AffiliateReferralSessionService {
	return c.affiliateReferralSessions
}

// AffiliatePayouts returns the AffiliatePayouts service.
func (c *Client) AffiliatePayouts() *AffiliatePayoutService {
	return c.affiliatePayouts
}

// Refunds returns the Refunds service.
func (c *Client) Refunds() *RefundService {
	return c.refunds
}

// Exports returns the Exports service.
func (c *Client) Exports() *ExportService {
	return c.exports
}

// Disputes returns the Disputes service.
func (c *Client) Disputes() *DisputeService {
	return c.disputes
}

// Entitlements returns the Entitlements service.
func (c *Client) Entitlements() *EntitlementService {
	return c.entitlements
}

// CustomerSessions returns the CustomerSessions service.
func (c *Client) CustomerSessions() *CustomerSessionService {
	return c.customerSessions
}

// CustomerPortal returns the CustomerPortal service.
func (c *Client) CustomerPortal() *CustomerPortalService {
	return c.customerPortal
}

// Events returns the Events service.
func (c *Client) Events() *EventService {
	return c.events
}

// WebhookPlatform returns the WebhookPlatform service.
func (c *Client) WebhookPlatform() *WebhookPlatformService {
	return c.webhookPlatform
}

// Account returns the Account service.
func (c *Client) Account() *AccountService {
	return c.account
}

// OAuthManagement returns the OAuthManagement service.
func (c *Client) OAuthManagement() *OAuthManagementService {
	return c.oAuthManagement
}

// Blacklists returns the Blacklists service.
func (c *Client) Blacklists() *BlacklistService {
	return c.blacklists
}

// Coupons returns the Coupons service.
func (c *Client) Coupons() *CouponService {
	return c.coupons
}

// Feedback returns the Feedback service.
func (c *Client) Feedback() *FeedbackService {
	return c.feedback
}

// Sections returns the Sections service.
func (c *Client) Sections() *SectionService {
	return c.sections
}

// Tickets returns the Tickets service.
func (c *Client) Tickets() *TicketService {
	return c.tickets
}

// TicketsMessages returns the TicketsMessages service.
func (c *Client) TicketsMessages() *TicketsMessageService {
	return c.ticketsMessages
}

// OAuth returns the OAuth service.
func (c *Client) OAuth() *OAuthService {
	return c.oAuth
}
