// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestStoreCustomDomains_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/store/custom-domains", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_list_custom_domains_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreCustomDomains().List(context.Background())
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreCustomDomains_Connect(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/store/custom-domains", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_custom_domain_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreCustomDomains().Connect(context.Background(), decodeTestParams[sellapp.StoreCustomDomainsConnectParams](t, "{\"domain\":\"test_domain\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreCustomDomains_Get(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/store/custom-domains/1", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_custom_domain_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreCustomDomains().Get(context.Background(), 1)
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreCustomDomains_Disconnect(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v2/store/custom-domains/1", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.StoreCustomDomains().Disconnect(context.Background(), 1)
	require.NoError(t, err)
}

func TestStoreCustomDomains_Refresh(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/store/custom-domains/1/refresh", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_custom_domain_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreCustomDomains().Refresh(context.Background(), 1)
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreCustomDomains_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.StoreCustomDomains().List(context.Background())
	require.IsType(t, &sellapp.AuthenticationError{}, err)
}

func TestStoreCustomDomains_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.StoreCustomDomains().List(context.Background())
	require.IsType(t, &sellapp.NotFoundError{}, err)
}

func TestStoreCustomDomains_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.StoreCustomDomains().List(context.Background())
	require.IsType(t, &sellapp.UnprocessableEntityError{}, err)
}
