// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"fmt"
	"net/url"
)

// StoreNotificationChannelService handles StoreNotificationChannels operations.
type StoreNotificationChannelService struct {
	client *Client
}

// List notification channels
// List dashboard notification destinations without exposing Discord webhook URLs. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreNotificationChannelService) List(ctx context.Context, opts ...RequestOption) (*SdkListNotificationChannelsResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("listNotificationChannels", false)}, opts...)
	var result SdkListNotificationChannelsResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", "/v2/store/notification-channels", nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *StoreNotificationChannelService) ListWithResponse(ctx context.Context, opts ...RequestOption) (*RawResponse[*SdkListNotificationChannelsResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.List(ctx, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// StoreNotificationChannelsCreateParams contains the parameters for Create.
type StoreNotificationChannelsCreateParams struct {
	Channel *CreateNotificationChannelRequestApplicationJSONPropertyChannel `json:"channel" url:"-"`
}

// Create a notification channel
// Create an email or Discord notification destination. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreNotificationChannelService) Create(ctx context.Context, params *StoreNotificationChannelsCreateParams, opts ...RequestOption) (*SdkCreateNotificationChannelResponseValue201ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("createNotificationChannel", false)}, opts...)
	var result SdkCreateNotificationChannelResponseValue201ApplicationJSON
	_, err := s.client.request(ctx, "POST", "/v2/store/notification-channels", nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkCreateNotificationChannelRequestApplicationJson\",\"properties\":{\"channel\":{\"kind\":\"object\",\"modelName\":\"CreateNotificationChannelRequestApplicationJsonPropertyChannel\",\"properties\":{},\"required\":[],\"additionalProperties\":true}},\"required\":[\"channel\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *StoreNotificationChannelService) CreateWithResponse(ctx context.Context, params *StoreNotificationChannelsCreateParams, opts ...RequestOption) (*RawResponse[*SdkCreateNotificationChannelResponseValue201ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Create(ctx, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Get retrieve a notification channel
// Manage one store-scoped notification channel by its identifier. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreNotificationChannelService) Get(ctx context.Context, notificationChannel string, opts ...RequestOption) (*SdkGetNotificationChannelResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getNotificationChannel", false)}, opts...)
	var result SdkGetNotificationChannelResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/store/notification-channels/%s", url.PathEscape(fmt.Sprint(notificationChannel))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *StoreNotificationChannelService) GetWithResponse(ctx context.Context, notificationChannel string, opts ...RequestOption) (*RawResponse[*SdkGetNotificationChannelResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, notificationChannel, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// StoreNotificationChannelsReplaceParams contains the parameters for Replace.
type StoreNotificationChannelsReplaceParams struct {
	Channel *ReplaceNotificationChannelRequestApplicationJSONPropertyChannel `json:"channel" url:"-"`
}

// Replace update a notification channel
// Manage one store-scoped notification channel by its identifier. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreNotificationChannelService) Replace(ctx context.Context, notificationChannel string, params *StoreNotificationChannelsReplaceParams, opts ...RequestOption) (*SdkReplaceNotificationChannelResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("replaceNotificationChannel", false)}, opts...)
	var result SdkReplaceNotificationChannelResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/v2/store/notification-channels/%s", url.PathEscape(fmt.Sprint(notificationChannel))), nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkReplaceNotificationChannelRequestApplicationJson\",\"properties\":{\"channel\":{\"kind\":\"object\",\"modelName\":\"ReplaceNotificationChannelRequestApplicationJsonPropertyChannel\",\"properties\":{},\"required\":[],\"additionalProperties\":true}},\"required\":[\"channel\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *StoreNotificationChannelService) ReplaceWithResponse(ctx context.Context, notificationChannel string, params *StoreNotificationChannelsReplaceParams, opts ...RequestOption) (*RawResponse[*SdkReplaceNotificationChannelResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Replace(ctx, notificationChannel, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// StoreNotificationChannelsUpdateParams contains the parameters for Update.
type StoreNotificationChannelsUpdateParams struct {
	Channel *UpdateNotificationChannelRequestApplicationJSONPropertyChannel `json:"channel" url:"-"`
}

// Update a notification channel
// Manage one store-scoped notification channel by its identifier. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreNotificationChannelService) Update(ctx context.Context, notificationChannel string, params *StoreNotificationChannelsUpdateParams, opts ...RequestOption) (*SdkUpdateNotificationChannelResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("updateNotificationChannel", false)}, opts...)
	var result SdkUpdateNotificationChannelResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/v2/store/notification-channels/%s", url.PathEscape(fmt.Sprint(notificationChannel))), nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkUpdateNotificationChannelRequestApplicationJson\",\"properties\":{\"channel\":{\"kind\":\"object\",\"modelName\":\"UpdateNotificationChannelRequestApplicationJsonPropertyChannel\",\"properties\":{\"type\":{\"kind\":\"enum\",\"values\":[\"email\",\"discord\"]},\"email\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"email\"},\"channel\":{\"kind\":\"primitive\",\"type\":\"string\"},\"webhook\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uri\"},\"allowed_notifications\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}}},\"required\":[],\"additionalProperties\":true,\"constraints\":{\"minProperties\":1}}},\"required\":[\"channel\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *StoreNotificationChannelService) UpdateWithResponse(ctx context.Context, notificationChannel string, params *StoreNotificationChannelsUpdateParams, opts ...RequestOption) (*RawResponse[*SdkUpdateNotificationChannelResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Update(ctx, notificationChannel, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Delete a notification channel
// Manage one store-scoped notification channel by its identifier. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreNotificationChannelService) Delete(ctx context.Context, notificationChannel string, opts ...RequestOption) error {
	opts = append([]RequestOption{withOperation("deleteNotificationChannel", false)}, opts...)
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/v2/store/notification-channels/%s", url.PathEscape(fmt.Sprint(notificationChannel))), nil, nil, nil, opts)
	return err
}

func (s *StoreNotificationChannelService) DeleteWithResponse(ctx context.Context, notificationChannel string, opts ...RequestOption) (*RawResponse[struct{}], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	if err := s.Delete(ctx, notificationChannel, captureOpts...); err != nil {
		return nil, err
	}
	return rawResponse(struct{}{}, metadata), nil
}
