// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestStoreSettings_Get(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/store/settings", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_store_settings_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreSettings().Get(context.Background())
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreSettings_ReplaceGeneral(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/store/settings/general", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_store_settings_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreSettings().ReplaceGeneral(context.Background(), decodeTestParams[sellapp.StoreSettingsReplaceGeneralParams](t, "{\"name\":\"Test\",\"visibility\":\"PUBLIC\",\"timezone\":\"test_timezone\",\"currency\":\"tes\",\"dark_mode\":\"light\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreSettings_UpdateGeneral(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/store/settings/general", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_store_settings_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreSettings().UpdateGeneral(context.Background(), decodeTestParams[sellapp.StoreSettingsUpdateGeneralParams](t, "{\"name\":\"Test\",\"visibility\":\"PUBLIC\",\"timezone\":\"test_timezone\",\"currency\":\"tes\",\"dark_mode\":\"light\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreSettings_ReplaceAnalytics(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/store/settings/analytics", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_store_settings_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreSettings().ReplaceAnalytics(context.Background(), decodeTestParams[sellapp.StoreSettingsReplaceAnalyticsParams](t, "{\"ga4_measurement_id\":\"ga4_measurement_id_01234\",\"meta_pixel_id\":\"meta_pixel_id_01234\",\"tiktok_pixel_id\":\"tiktok_pixel_id_01234\",\"ga4_api_secret\":\"test_ga4_api_secret\",\"meta_access_token\":\"test_meta_access_token\",\"tiktok_access_token\":\"test_tiktok_access_token\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreSettings_UpdateAnalytics(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/store/settings/analytics", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_store_settings_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreSettings().UpdateAnalytics(context.Background(), decodeTestParams[sellapp.StoreSettingsUpdateAnalyticsParams](t, "{\"ga4_measurement_id\":\"ga4_measurement_id_01234\",\"meta_pixel_id\":\"meta_pixel_id_01234\",\"tiktok_pixel_id\":\"tiktok_pixel_id_01234\",\"ga4_api_secret\":\"test_ga4_api_secret\",\"meta_access_token\":\"test_meta_access_token\",\"tiktok_access_token\":\"test_tiktok_access_token\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreSettings_ReplaceMarketing(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/store/settings/marketing", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_store_settings_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreSettings().ReplaceMarketing(context.Background(), decodeTestParams[sellapp.StoreSettingsReplaceMarketingParams](t, "{\"abandoned_cart\":{\"enabled\":true,\"min_total_cents\":1,\"max_total_cents\":1,\"reminders\":[{\"after_hours\":1}],\"incentive_mode\":\"none\",\"coupon_id\":1,\"send_incentive_on_step\":1}}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreSettings_UpdateMarketing(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/store/settings/marketing", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_get_store_settings_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.StoreSettings().UpdateMarketing(context.Background(), decodeTestParams[sellapp.StoreSettingsUpdateMarketingParams](t, "{\"abandoned_cart\":{\"enabled\":true,\"min_total_cents\":1,\"max_total_cents\":1,\"reminders\":[{\"after_hours\":1}],\"incentive_mode\":\"none\",\"coupon_id\":1,\"send_incentive_on_step\":1}}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestStoreSettings_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.StoreSettings().Get(context.Background())
	require.IsType(t, &sellapp.AuthenticationError{}, err)
}

func TestStoreSettings_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.StoreSettings().Get(context.Background())
	require.IsType(t, &sellapp.NotFoundError{}, err)
}

func TestStoreSettings_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.StoreSettings().Get(context.Background())
	require.IsType(t, &sellapp.UnprocessableEntityError{}, err)
}
