// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"fmt"
	"net/url"
)

// StoreCustomDomainService handles StoreCustomDomains operations.
type StoreCustomDomainService struct {
	client *Client
}

// List custom domains
// List the current store's custom-domain connection states and DNS verification records. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreCustomDomainService) List(ctx context.Context, opts ...RequestOption) (*SdkListCustomDomainsResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("listCustomDomains", false)}, opts...)
	var result SdkListCustomDomainsResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", "/v2/store/custom-domains", nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *StoreCustomDomainService) ListWithResponse(ctx context.Context, opts ...RequestOption) (*RawResponse[*SdkListCustomDomainsResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.List(ctx, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// StoreCustomDomainsConnectParams contains the parameters for Connect.
type StoreCustomDomainsConnectParams struct {
	// Domain is the custom domain as a hostname or URL.
	Domain string `json:"domain" url:"-"`
}

// Connect a custom domain
// Connect a hostname through SellApp's managed Cloudflare custom-hostname flow. IP addresses, wildcard domains, credentials, ports, queries, and fragments are rejected. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreCustomDomainService) Connect(ctx context.Context, params *StoreCustomDomainsConnectParams, opts ...RequestOption) (*SdkConnectCustomDomainResponseValue201ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("connectCustomDomain", false)}, opts...)
	var result SdkConnectCustomDomainResponseValue201ApplicationJSON
	_, err := s.client.request(ctx, "POST", "/v2/store/custom-domains", nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkConnectCustomDomainRequestApplicationJson\",\"properties\":{\"domain\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":253}}},\"required\":[\"domain\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *StoreCustomDomainService) ConnectWithResponse(ctx context.Context, params *StoreCustomDomainsConnectParams, opts ...RequestOption) (*RawResponse[*SdkConnectCustomDomainResponseValue201ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Connect(ctx, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Get retrieve a custom domain
// Retrieve a custom domain. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreCustomDomainService) Get(ctx context.Context, customDomain int, opts ...RequestOption) (*SdkGetCustomDomainResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getCustomDomain", false)}, opts...)
	var result SdkGetCustomDomainResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/store/custom-domains/%s", url.PathEscape(fmt.Sprint(customDomain))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *StoreCustomDomainService) GetWithResponse(ctx context.Context, customDomain int, opts ...RequestOption) (*RawResponse[*SdkGetCustomDomainResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, customDomain, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Disconnect a custom domain
// Disconnect a custom domain. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreCustomDomainService) Disconnect(ctx context.Context, customDomain int, opts ...RequestOption) error {
	opts = append([]RequestOption{withOperation("disconnectCustomDomain", false)}, opts...)
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/v2/store/custom-domains/%s", url.PathEscape(fmt.Sprint(customDomain))), nil, nil, nil, opts)
	return err
}

func (s *StoreCustomDomainService) DisconnectWithResponse(ctx context.Context, customDomain int, opts ...RequestOption) (*RawResponse[struct{}], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	if err := s.Disconnect(ctx, customDomain, captureOpts...); err != nil {
		return nil, err
	}
	return rawResponse(struct{}{}, metadata), nil
}

// Refresh custom domain status
// Ask Cloudflare to re-run custom-hostname validation and persist the latest DNS and SSL state. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *StoreCustomDomainService) Refresh(ctx context.Context, customDomain int, opts ...RequestOption) (*SdkRefreshCustomDomainStatusResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("refreshCustomDomainStatus", false)}, opts...)
	var result SdkRefreshCustomDomainStatusResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/v2/store/custom-domains/%s/refresh", url.PathEscape(fmt.Sprint(customDomain))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *StoreCustomDomainService) RefreshWithResponse(ctx context.Context, customDomain int, opts ...RequestOption) (*RawResponse[*SdkRefreshCustomDomainStatusResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Refresh(ctx, customDomain, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
