// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
)

// TicketsMessageService handles TicketsMessages operations.
type TicketsMessageService struct {
	client *Client
}

// TicketsMessagesListParams contains the parameters for List.
type TicketsMessagesListParams struct {
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
}

// List all ticket messages
// Read a ticket's conversation, 15 messages per page by default.
func (s *TicketsMessageService) List(ctx context.Context, ticket int, params *TicketsMessagesListParams, opts ...RequestOption) *Iterator[ListTicketMessagesResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("listTicketMessages", false)}, opts...)
	return newIterator[ListTicketMessagesResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", fmt.Sprintf("/v1/tickets/%s/messages", url.PathEscape(fmt.Sprint(ticket))), params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *TicketsMessageService) ListWithResponse(ctx context.Context, ticket int, params *TicketsMessagesListParams, opts ...RequestOption) (*RawResponse[*Iterator[ListTicketMessagesResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, ticket, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// TicketsMessagesReplyParams contains the parameters for Reply.
type TicketsMessagesReplyParams struct {
	Content string `json:"content" url:"-"`
}

// Reply to ticket
// Add a seller reply to a support conversation.
func (s *TicketsMessageService) Reply(ctx context.Context, ticket int, params *TicketsMessagesReplyParams, opts ...RequestOption) (*SdkReplyToTicketResponseValue201ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("replyToTicket", false)}, opts...)
	var result SdkReplyToTicketResponseValue201ApplicationJSON
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/v1/tickets/%s/messages", url.PathEscape(fmt.Sprint(ticket))), nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkReplyToTicketRequestApplicationJson\",\"properties\":{\"content\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"content\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *TicketsMessageService) ReplyWithResponse(ctx context.Context, ticket int, params *TicketsMessagesReplyParams, opts ...RequestOption) (*RawResponse[*SdkReplyToTicketResponseValue201ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Reply(ctx, ticket, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// Get retrieve specific ticket message
// Retrieve one message using its ticket ID and message ID.
func (s *TicketsMessageService) Get(ctx context.Context, ticket int, message int, opts ...RequestOption) (*SdkGetTicketMessageResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("getTicketMessage", false)}, opts...)
	var result SdkGetTicketMessageResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/tickets/%s/messages/%s", url.PathEscape(fmt.Sprint(ticket)), url.PathEscape(fmt.Sprint(message))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *TicketsMessageService) GetWithResponse(ctx context.Context, ticket int, message int, opts ...RequestOption) (*RawResponse[*SdkGetTicketMessageResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Get(ctx, ticket, message, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// TicketsMessagesSearchParams contains the parameters for Search.
type TicketsMessagesSearchParams struct {
	Filters  []*SearchTicketMessagesRequestApplicationJSONPropertyFiltersItem  `json:"filters,omitempty" url:"-"`
	Sort     []*SearchTicketMessagesRequestApplicationJSONPropertySortItem     `json:"sort,omitempty" url:"-"`
	Search   *SearchTicketMessagesRequestApplicationJSONPropertySearch         `json:"search,omitempty" url:"-"`
	Includes []*SearchTicketMessagesRequestApplicationJSONPropertyIncludesItem `json:"includes,omitempty" url:"-"`
}

// MarshalJSON implements json.Marshaler for TicketsMessagesSearchParams.
func (p TicketsMessagesSearchParams) MarshalJSON() ([]byte, error) {
	type Alias TicketsMessagesSearchParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if p.Filters == nil && p.Sort == nil && p.Includes == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Filters != nil {
		m["filters"] = p.Filters
	}
	if p.Sort != nil {
		m["sort"] = p.Sort
	}
	if p.Includes != nil {
		m["includes"] = p.Includes
	}
	return json.Marshal(m)
}

// Search ticket messages
// Search a ticket's messages using JSON body filters, search terms, includes, and sort instructions.
func (s *TicketsMessageService) Search(ctx context.Context, ticket int, params *TicketsMessagesSearchParams, opts ...RequestOption) *Iterator[SearchTicketMessagesResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("searchTicketMessages", false)}, opts...)
	return newIterator[SearchTicketMessagesResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "POST", fmt.Sprintf("/v1/tickets/%s/messages/search", url.PathEscape(fmt.Sprint(ticket))), nil, "after", "data", opts, nil, func() any {
		if params == nil {
			return nil
		}
		return schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkSearchTicketMessagesRequestApplicationJson\",\"properties\":{\"filters\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchTicketMessagesRequestApplicationJsonPropertyFiltersItem\",\"properties\":{\"field\":{\"kind\":\"primitive\",\"type\":\"string\"},\"operator\":{\"kind\":\"primitive\",\"type\":\"string\"},\"value\":{\"kind\":\"primitive\",\"type\":\"unknown\"},\"type\":{\"kind\":\"enum\",\"values\":[\"and\",\"or\"]},\"nested\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchTicketMessagesRequestApplicationJsonPropertyFiltersItemPropertyNestedItem\",\"properties\":{},\"required\":[],\"additionalProperties\":true}}},\"required\":[],\"additionalProperties\":true}},\"sort\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchTicketMessagesRequestApplicationJsonPropertySortItem\",\"properties\":{\"field\":{\"kind\":\"primitive\",\"type\":\"string\"},\"direction\":{\"kind\":\"enum\",\"values\":[\"asc\",\"desc\"]}},\"required\":[\"field\"],\"additionalProperties\":true}},\"search\":{\"kind\":\"object\",\"modelName\":\"SearchTicketMessagesRequestApplicationJsonPropertySearch\",\"properties\":{\"value\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"case_sensitive\":{\"kind\":\"primitive\",\"type\":\"boolean\"}},\"required\":[],\"additionalProperties\":true},\"includes\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"SearchTicketMessagesRequestApplicationJsonPropertyIncludesItem\",\"properties\":{\"relation\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"relation\"],\"additionalProperties\":true}}},\"required\":[],\"additionalProperties\":true}"))
	}())
}

func (s *TicketsMessageService) SearchWithResponse(ctx context.Context, ticket int, params *TicketsMessagesSearchParams, opts ...RequestOption) (*RawResponse[*Iterator[SearchTicketMessagesResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.Search(ctx, ticket, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// TicketsMessagesV2ListTicketMessagesParams contains the parameters for V2ListTicketMessages.
type TicketsMessagesV2ListTicketMessagesParams struct {
	// Limit is number of items to return per page.
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
	// Page is page number to return.
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
}

// V2ListTicketMessages list all ticket messages
// Read a ticket's conversation, 15 messages per page by default. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *TicketsMessageService) V2ListTicketMessages(ctx context.Context, ticket int, params *TicketsMessagesV2ListTicketMessagesParams, opts ...RequestOption) *Iterator[V2ListTicketMessagesResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("v2ListTicketMessages", false)}, opts...)
	return newIterator[V2ListTicketMessagesResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", fmt.Sprintf("/v2/tickets/%s/messages", url.PathEscape(fmt.Sprint(ticket))), params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *TicketsMessageService) V2ListTicketMessagesWithResponse(ctx context.Context, ticket int, params *TicketsMessagesV2ListTicketMessagesParams, opts ...RequestOption) (*RawResponse[*Iterator[V2ListTicketMessagesResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.V2ListTicketMessages(ctx, ticket, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// TicketsMessagesV2ReplyToTicketParams contains the parameters for V2ReplyToTicket.
type TicketsMessagesV2ReplyToTicketParams struct {
	Content string `json:"content" url:"-"`
}

// V2ReplyToTicket reply to ticket
// Add a seller reply to a support conversation. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *TicketsMessageService) V2ReplyToTicket(ctx context.Context, ticket int, params *TicketsMessagesV2ReplyToTicketParams, opts ...RequestOption) (*SdkV2ReplyToTicketResponseValue201ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("v2ReplyToTicket", false)}, opts...)
	var result SdkV2ReplyToTicketResponseValue201ApplicationJSON
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/v2/tickets/%s/messages", url.PathEscape(fmt.Sprint(ticket))), nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkV2ReplyToTicketRequestApplicationJson\",\"properties\":{\"content\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"content\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *TicketsMessageService) V2ReplyToTicketWithResponse(ctx context.Context, ticket int, params *TicketsMessagesV2ReplyToTicketParams, opts ...RequestOption) (*RawResponse[*SdkV2ReplyToTicketResponseValue201ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.V2ReplyToTicket(ctx, ticket, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// TicketsMessagesV2SearchTicketMessagesParams contains the parameters for V2SearchTicketMessages.
type TicketsMessagesV2SearchTicketMessagesParams struct {
	Filters  []*V2SearchTicketMessagesRequestApplicationJSONPropertyFiltersItem  `json:"filters,omitempty" url:"-"`
	Sort     []*V2SearchTicketMessagesRequestApplicationJSONPropertySortItem     `json:"sort,omitempty" url:"-"`
	Search   *V2SearchTicketMessagesRequestApplicationJSONPropertySearch         `json:"search,omitempty" url:"-"`
	Includes []*V2SearchTicketMessagesRequestApplicationJSONPropertyIncludesItem `json:"includes,omitempty" url:"-"`
}

// MarshalJSON implements json.Marshaler for TicketsMessagesV2SearchTicketMessagesParams.
func (p TicketsMessagesV2SearchTicketMessagesParams) MarshalJSON() ([]byte, error) {
	type Alias TicketsMessagesV2SearchTicketMessagesParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if p.Filters == nil && p.Sort == nil && p.Includes == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.Filters != nil {
		m["filters"] = p.Filters
	}
	if p.Sort != nil {
		m["sort"] = p.Sort
	}
	if p.Includes != nil {
		m["includes"] = p.Includes
	}
	return json.Marshal(m)
}

// V2SearchTicketMessages search ticket messages
// Search a ticket's messages using JSON body filters, search terms, includes, and sort instructions. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *TicketsMessageService) V2SearchTicketMessages(ctx context.Context, ticket int, params *TicketsMessagesV2SearchTicketMessagesParams, opts ...RequestOption) *Iterator[V2SearchTicketMessagesResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("v2SearchTicketMessages", false)}, opts...)
	return newIterator[V2SearchTicketMessagesResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "POST", fmt.Sprintf("/v2/tickets/%s/messages/search", url.PathEscape(fmt.Sprint(ticket))), nil, "after", "data", opts, nil, func() any {
		if params == nil {
			return nil
		}
		return schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkV2SearchTicketMessagesRequestApplicationJson\",\"properties\":{\"filters\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"V2SearchTicketMessagesRequestApplicationJsonPropertyFiltersItem\",\"properties\":{\"field\":{\"kind\":\"primitive\",\"type\":\"string\"},\"operator\":{\"kind\":\"primitive\",\"type\":\"string\"},\"value\":{\"kind\":\"primitive\",\"type\":\"unknown\"},\"type\":{\"kind\":\"enum\",\"values\":[\"and\",\"or\"]},\"nested\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"V2SearchTicketMessagesRequestApplicationJsonPropertyFiltersItemPropertyNestedItem\",\"properties\":{},\"required\":[],\"additionalProperties\":true}}},\"required\":[],\"additionalProperties\":true}},\"sort\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"V2SearchTicketMessagesRequestApplicationJsonPropertySortItem\",\"properties\":{\"field\":{\"kind\":\"primitive\",\"type\":\"string\"},\"direction\":{\"kind\":\"enum\",\"values\":[\"asc\",\"desc\"]}},\"required\":[\"field\"],\"additionalProperties\":true}},\"search\":{\"kind\":\"object\",\"modelName\":\"V2SearchTicketMessagesRequestApplicationJsonPropertySearch\",\"properties\":{\"value\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"case_sensitive\":{\"kind\":\"primitive\",\"type\":\"boolean\"}},\"required\":[],\"additionalProperties\":true},\"includes\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"V2SearchTicketMessagesRequestApplicationJsonPropertyIncludesItem\",\"properties\":{\"relation\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"relation\"],\"additionalProperties\":true}}},\"required\":[],\"additionalProperties\":true}"))
	}())
}

func (s *TicketsMessageService) V2SearchTicketMessagesWithResponse(ctx context.Context, ticket int, params *TicketsMessagesV2SearchTicketMessagesParams, opts ...RequestOption) (*RawResponse[*Iterator[V2SearchTicketMessagesResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.V2SearchTicketMessages(ctx, ticket, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}

// V2GetTicketMessage retrieve specific ticket message
// Retrieve one message using its ticket ID and message ID. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *TicketsMessageService) V2GetTicketMessage(ctx context.Context, ticket int, message int, opts ...RequestOption) (*SdkV2GetTicketMessageResponseValue200ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("v2GetTicketMessage", false)}, opts...)
	var result SdkV2GetTicketMessageResponseValue200ApplicationJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v2/tickets/%s/messages/%s", url.PathEscape(fmt.Sprint(ticket)), url.PathEscape(fmt.Sprint(message))), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *TicketsMessageService) V2GetTicketMessageWithResponse(ctx context.Context, ticket int, message int, opts ...RequestOption) (*RawResponse[*SdkV2GetTicketMessageResponseValue200ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.V2GetTicketMessage(ctx, ticket, message, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
