// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"fmt"
	"net/url"
)

// WalletTransactionService handles WalletTransactions operations.
type WalletTransactionService struct {
	client *Client
}

// WalletTransactionsListParams contains the parameters for List.
type WalletTransactionsListParams struct {
	// Defaults to 1.
	Page *int `url:"page,omitempty" json:"-"`
	// Defaults to 15.
	Limit *int `url:"limit,omitempty" json:"-"`
}

// List wallet transactions
// Read the complete wallet history for one customer in the selected store, newest first. Requires the wallet or wallet:write API-key ability and store wallet permission. Amounts and balances are integer USD cents: 2500 means $25.00. A wallet with no entries returns an empty data array; an unknown wallet returns 404. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *WalletTransactionService) List(ctx context.Context, customer int, params *WalletTransactionsListParams, opts ...RequestOption) *Iterator[ListWalletTransactionsResponseValue200ApplicationJSONPropertyDataItem] {
	opts = append([]RequestOption{withOperation("listWalletTransactions", false)}, opts...)
	return newIterator[ListWalletTransactionsResponseValue200ApplicationJSONPropertyDataItem](ctx, s.client, "GET", fmt.Sprintf("/v2/wallets/%s/transactions", url.PathEscape(fmt.Sprint(customer))), params, "after", "data", opts, map[string]string{"limit": "15"})
}

func (s *WalletTransactionService) ListWithResponse(ctx context.Context, customer int, params *WalletTransactionsListParams, opts ...RequestOption) (*RawResponse[*Iterator[ListWalletTransactionsResponseValue200ApplicationJSONPropertyDataItem]], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value := s.List(ctx, customer, params, captureOpts...)
	if err := value.Err(); err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
