// Code generated by oagen. DO NOT EDIT.

package sellapp

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
)

// WalletTopupService handles WalletTopups operations.
type WalletTopupService struct {
	client *Client
}

// WalletTopupsCreateParams contains the parameters for Create.
type WalletTopupsCreateParams struct {
	// AmountCents is deposit in integer USD cents: 2500 means $25.00. The store's minimum and maximum top-up amounts also apply.
	AmountCents int `json:"amount_cents" url:"-"`
	// PaymentMethod is one enabled payment gateway allowed by the store's wallet settings for USD. CUSTOM_PAYMENT_METHOD also requires custom_payment_method_id.
	PaymentMethod SdkCreateWalletTopUpRequestApplicationJSONPaymentMethod `json:"payment_method" url:"-"`
	// CustomPaymentMethodID is enabled custom method in this store. Required for CUSTOM_PAYMENT_METHOD; omit or use null for other gateways.
	CustomPaymentMethodID *string `json:"custom_payment_method_id,omitempty" url:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for WalletTopupsCreateParams.
func (p WalletTopupsCreateParams) MarshalJSON() ([]byte, error) {
	type Alias WalletTopupsCreateParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if len(p.NullFields) == 0 {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	nullable := map[string]bool{
		"custom_payment_method_id": true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("WalletTopupsCreateParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// Create a wallet top-up payment link
// Create a paid USD top-up for an existing customer and return data.checkout_url for the customer to pay. Creating a link leaves the wallet balance unchanged. Requires both wallet:write and charge API-key abilities and both store wallet and charge permissions. The wallet must be enabled and unfrozen, and the amount and selected method must satisfy the store's wallet settings. Payment completion credits the deposit and any bonus saved at creation exactly once; custom-method modifiers do not change the deposit. Browser returns and submitted payment proof do not prove payment. The return and cancel destination is the store's customer portal wallet. Currency, metadata, and redirect overrides are unsupported. Send an Idempotency-Key and reuse the same key and request for response replay within 24 hours. Changed input returns 409. For an uncertain provider outcome, inspect the charge before starting another top-up. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
func (s *WalletTopupService) Create(ctx context.Context, customer int, params *WalletTopupsCreateParams, opts ...RequestOption) (*SdkCreateWalletTopUpResponseValue201ApplicationJSON, error) {
	opts = append([]RequestOption{withOperation("createWalletTopUp", true)}, opts...)
	var result SdkCreateWalletTopUpResponseValue201ApplicationJSON
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/v2/wallets/%s/top-ups", url.PathEscape(fmt.Sprint(customer))), nil, schemaValidatedBody(params, mustRuntimeSchema("{\"kind\":\"object\",\"modelName\":\"SdkCreateWalletTopUpRequestApplicationJson\",\"properties\":{\"amount_cents\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1,\"maximum\":999999999999}},\"payment_method\":{\"kind\":\"enum\",\"values\":[\"AUTHNET\",\"BTCPAY\",\"CASHAPP\",\"COINBASE\",\"PADDLE\",\"PAYDASH\",\"PAYPAL\",\"PAYSTACK\",\"SQUARE\",\"STRIPE\",\"VENMO\",\"NMI\",\"MERCADO_PAGO\",\"MOLLIE\",\"RAZORPAY\",\"CUSTOM_PAYMENT_METHOD\",\"LIFI\",\"BTC\",\"LTC\",\"ETH\",\"XMR\",\"SOL\",\"ADA\",\"BNB\",\"TRX\",\"MATIC\",\"ETH_USDT\",\"ETH_USDC\",\"ETH_UNI\",\"ETH_SHIB\",\"ETH_DAI\",\"BNB_USDT\",\"BNB_USDC\",\"TRX_USDT\",\"TRX_USDC\",\"SOL_USDT\",\"SOL_USDC\"]},\"custom_payment_method_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minLength\":26,\"maxLength\":26,\"pattern\":\"^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$\"}}}},\"required\":[\"amount_cents\",\"payment_method\"],\"additionalProperties\":true}")), &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (s *WalletTopupService) CreateWithResponse(ctx context.Context, customer int, params *WalletTopupsCreateParams, opts ...RequestOption) (*RawResponse[*SdkCreateWalletTopUpResponseValue201ApplicationJSON], error) {
	var metadata *responseMetadata
	captureOpts := append(opts, withResponseMetadata(&metadata))
	value, err := s.Create(ctx, customer, params, captureOpts...)
	if err != nil {
		return nil, err
	}
	return rawResponse(value, metadata), nil
}
