// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestWalletTopups_Create(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/wallets/1/top-ups", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_create_wallet_top_up_response_value_201_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.WalletTopups().Create(context.Background(), 1, decodeTestParams[sellapp.WalletTopupsCreateParams](t, "{\"amount_cents\":1,\"payment_method\":\"AUTHNET\",\"custom_payment_method_id\":\"00000000000000000000000000\"}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestWalletTopups_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.WalletTopups().Create(context.Background(), 1, decodeTestParams[sellapp.WalletTopupsCreateParams](t, "{\"amount_cents\":1,\"payment_method\":\"AUTHNET\",\"custom_payment_method_id\":\"00000000000000000000000000\"}"))
	require.IsType(t, &sellapp.AuthenticationError{}, err)
}

func TestWalletTopups_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.WalletTopups().Create(context.Background(), 1, decodeTestParams[sellapp.WalletTopupsCreateParams](t, "{\"amount_cents\":1,\"payment_method\":\"AUTHNET\",\"custom_payment_method_id\":\"00000000000000000000000000\"}"))
	require.IsType(t, &sellapp.NotFoundError{}, err)
}

func TestWalletTopups_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.WalletTopups().Create(context.Background(), 1, decodeTestParams[sellapp.WalletTopupsCreateParams](t, "{\"amount_cents\":1,\"payment_method\":\"AUTHNET\",\"custom_payment_method_id\":\"00000000000000000000000000\"}"))
	require.IsType(t, &sellapp.UnprocessableEntityError{}, err)
}
