// Code generated by oagen. DO NOT EDIT.

package sellapp_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/sellapp/sellapp-go"
)

var _ = os.ReadFile
var _ = json.Unmarshal
var _ = io.ReadAll

func TestWalletBonusTiers_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/v2/wallet-bonus-tiers", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_list_wallet_bonus_tiers_response_value_200_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.WalletBonusTiers().List(context.Background())
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestWalletBonusTiers_Create(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/wallet-bonus-tiers", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_create_wallet_bonus_tier_response_value_201_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.WalletBonusTiers().Create(context.Background(), decodeTestParams[sellapp.WalletBonusTiersCreateParams](t, "{\"minimum_top_up_cents\":1,\"bonus_kind\":\"fixed\",\"fixed_bonus_cents\":1,\"percent_basis\":1,\"maximum_bonus_cents\":1,\"priority\":1,\"is_active\":true}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestWalletBonusTiers_Replace(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/v2/wallet-bonus-tiers/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_create_wallet_bonus_tier_response_value_201_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.WalletBonusTiers().Replace(context.Background(), 1, decodeTestParams[sellapp.WalletBonusTiersReplaceParams](t, "{\"minimum_top_up_cents\":1,\"bonus_kind\":\"fixed\",\"fixed_bonus_cents\":1,\"percent_basis\":1,\"maximum_bonus_cents\":1,\"priority\":1,\"is_active\":true}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestWalletBonusTiers_Update(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/v2/wallet-bonus-tiers/1", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_create_wallet_bonus_tier_response_value_201_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.WalletBonusTiers().Update(context.Background(), 1, decodeTestParams[sellapp.WalletBonusTiersUpdateParams](t, "{\"minimum_top_up_cents\":1,\"bonus_kind\":\"fixed\",\"fixed_bonus_cents\":1,\"percent_basis\":1,\"maximum_bonus_cents\":1,\"priority\":1,\"is_active\":true}"))
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestWalletBonusTiers_Archive(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/v2/wallet-bonus-tiers/1", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	err := client.WalletBonusTiers().Archive(context.Background(), 1)
	require.NoError(t, err)
}

func TestWalletBonusTiers_Restore(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/v2/wallet-bonus-tiers/1/restore", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/sdk_create_wallet_bonus_tier_response_value_201_application_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	result, err := client.WalletBonusTiers().Restore(context.Background(), 1)
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestWalletBonusTiers_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.WalletBonusTiers().List(context.Background())
	require.IsType(t, &sellapp.AuthenticationError{}, err)
}

func TestWalletBonusTiers_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.WalletBonusTiers().List(context.Background())
	require.IsType(t, &sellapp.NotFoundError{}, err)
}

func TestWalletBonusTiers_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := sellapp.NewClient("sk_test", "store_test", sellapp.WithBaseURL(server.URL))
	_, err := client.WalletBonusTiers().List(context.Background())
	require.IsType(t, &sellapp.UnprocessableEntityError{}, err)
}
