// Code generated by oagen. DO NOT EDIT.

package main

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"time"

	"github.com/sellapp/sellapp-go"
)

func firstRequest(ctx context.Context, client *sellapp.Client, out io.Writer) error {
	limit := 1
	products := client.Products().List(ctx, &sellapp.ProductsListParams{Limit: &limit})
	if products.Next() {
		product := products.Current()
		fmt.Fprintf(out, "%d: %s\n", product.ID, product.Title)
	} else if products.Err() == nil {
		fmt.Fprintln(out, "No products yet. Your connection is ready.")
	}
	return products.Err()
}

func paginate(ctx context.Context, client *sellapp.Client, out io.Writer) error {
	limit := 15
	products := client.Products().List(ctx, &sellapp.ProductsListParams{Limit: &limit})
	// Keep this example bounded: inspect at most 30 products.
	for count := 0; count < 30 && products.Next(); count++ {
		fmt.Fprintf(out, "%d: %s\n", products.Current().ID, products.Current().Title)
	}
	return products.Err()
}

func reportError(err error, out io.Writer) {
	var authentication *sellapp.AuthenticationError
	var rateLimit *sellapp.RateLimitExceededError
	var timeout *sellapp.TimeoutError
	switch {
	case errors.As(err, &authentication):
		fmt.Fprintf(out, "Check the API key and store: %s (request %s)\n", authentication.Message, authentication.RequestID)
	case errors.As(err, &rateLimit):
		fmt.Fprintf(out, "Rate limited: %s (request %s)\n", rateLimit.Message, rateLimit.RequestID)
	case errors.As(err, &timeout):
		fmt.Fprintln(out, "Request timed out:", timeout)
	default:
		fmt.Fprintln(out, "Request failed:", err)
	}
}

func run(out io.Writer) error {
	// An explicit URL keeps accidental example runs from reaching production.
	baseURL := os.Getenv("SELLAPP_API_BASE_URL")
	if baseURL == "" || os.Getenv("SELLAPP_API_KEY") == "" || os.Getenv("SELLAPP_STORE") == "" {
		return fmt.Errorf("set SELLAPP_API_BASE_URL, SELLAPP_API_KEY, and SELLAPP_STORE")
	}
	client := sellapp.NewClient("", "", sellapp.WithBaseURL(baseURL), sellapp.WithMaxRetries(0))
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if os.Getenv("SELLAPP_EXAMPLE_MODE") == "pagination" {
		return paginate(ctx, client, out)
	}
	return firstRequest(ctx, client, out)
}

func main() {
	if err := run(os.Stdout); err != nil {
		reportError(err, os.Stderr)
		os.Exit(1)
	}
}
